In [ ]:
import requests
from bs4 import BeautifulSoup
import time
import pandas as pd
import os
from urllib.parse import urljoin

In [ ]:
# url = "https://oskelly.ru/catalog/zhenskoe/odezhda"
headers = {"User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
# r = requests.get(url, headers=headers)
# r

In [ ]:
from google.colab import drive
drive.mount('/content/udrive')

Mounted at /content/udrive

In [ ]:
images_dir = "/content/udrive/MyDrive/GP5/oskelly_imagess"
os.makedirs(images_dir, exist_ok=True)

In [ ]:
# soup = BeautifulSoup(r.text, 'html')

In [ ]:
def get_main_product_image_url(soup, base_url="https://oskelly.ru"):
    candidates = []

    for img in soup.find_all("img"):
        src = img.get("src")
        srcset = img.get("srcset")
        class_name = " ".join(img.get("class", []))

        is_product_gallery = (
            "osk-product-gallery__main-swiper-image" in class_name
            or "osk-product-gallery__thumbs-swiper-image" in class_name
            or "osk-product-card__card-img-pic" in class_name
        )

        if src:
            full_url = urljoin(base_url, src)

            if "/product/" in full_url and full_url.startswith("http"):
                if is_product_gallery:
                    return full_url
                candidates.append(full_url)

        if srcset:
            for part in srcset.split(","):
                srcset_url = part.strip().split(" ")[0]
                full_url = urljoin(base_url, srcset_url)

                if "/product/" in full_url and full_url.startswith("http"):
                    if is_product_gallery:
                        return full_url
                    candidates.append(full_url)

    if candidates:
        return candidates[0]

    return None

In [ ]:
def download_main_product_image(image_url, item_id, images_dir=images_dir):

    if image_url is None:
      return None

    ext = ".jpg"

    if ".png" in image_url.lower():
      ext = ".png"
    elif ".jpeg" in image_url.lower():
      ext = ".jpeg"

    image_path = os.path.join(images_dir, f"{item_id}{ext}")

    if os.path.exists(image_path):
      return image_path

    img_response = requests.get(image_url,headers={"User-Agent": headers["User-Agent"],"Referer": "https://oskelly.ru"},timeout=20)

    if img_response.status_code == 200 and img_response.content:
      with open(image_path, "wb") as f:
          f.write(img_response.content)

      return image_path

    return None

In [ ]:
# soup.find_all('a')[22]

In [ ]:
# items = soup.find_all("a", class_="osk-product-card__card-img")

In [ ]:
# items[0].get('href')

In [ ]:
# len(items)

In [ ]:
items = []
for i in range(1, 50):
  url = 'https://oskelly.ru/catalog/zhenskoe/odezhda?page=' + str(i)
  oskelly = requests.get(url, headers=headers)
  soup = BeautifulSoup(oskelly.text, 'html')
  page = soup.find_all("a", class_="osk-product-card__card-img")
  for elem in page:
    items.append(elem.get('href'))
  time.sleep(0.5)

In [ ]:
pd.Series(items).to_excel('links50.xlsx', index=False)

In [ ]:
for i in range(50, 101):
  url = 'https://oskelly.ru/catalog/zhenskoe/odezhda?page=' + str(i)
  oskelly = requests.get(url, headers=headers)
  soup = BeautifulSoup(oskelly.text, 'html')
  page = soup.find_all("a", class_="osk-product-card__card-img")
  for elem in page:
    items.append(elem.get('href'))
  time.sleep(0.5)

In [ ]:
pd.Series(items).to_excel('links100.xlsx', index=False)

In [ ]:
items

['/products/rubashka-miu-miu-new-5272379',
 '/products/kupalnik-christian-dior-new-5914800',
 '/products/trenchplashch-burberry-new-4201550',
 '/products/sportivnye-bryuki-i-shorty-aloyoga-new-5146377',
 '/products/mayka-aloyoga-new-5271514',
 '/products/pukhovik-aloyoga-new-4855327',
 '/products/futbolka-acnestudios-new-3790125',
 '/products/futbolka-stussy-new-3684331',
 '/products/futbolka-acnestudios-new-3664015',
 '/products/khuditolstovka-acnestudios-new-5582336',
 '/products/futbolka-acnestudios-new-3369121',
 '/products/futbolka-acnestudios-new-3896276',
 '/products/kurtka-barbour-new-5848065',
 '/products/dzhinsy-slim-pierre-balmain-pre-owned-2009924',
 '/products/pryamye-bryuki-alaia-new-3645389',
 '/products/kurtka-goldengoosedeluxebrand-new-4777181',
 '/products/futbolka-givenchy-new-4766815',
 '/products/dzhemper--sviter-poloralphlauren-new-5062231',
 '/products/trenchplashch-burberry-new-5914552',
 '/products/khuditolstovka-stussy-new-3364573',
 '/products/futbolka-acnestudios-new-3368630',
 '/products/futbolka-acnestudios-new-3368506',
 '/products/futbolka-acnestudios-new-3694600',
 '/products/pryamye-dzhinsy-acnestudios-new-3368321',
 '/products/futbolka-acnestudios-new-3368150',
 '/products/futbolka-loewe-new-3425404',
 '/products/sportivnye-bryuki-i-shorty-aloyoga-new-2906017',
 '/products/mayka-aloyoga-new-3090070',
 '/products/sportivnye-bryuki-i-shorty-aloyoga-new-5270527',
 '/products/kardigan-aloyoga-new-5429015',
 '/products/sportivnaya-kurtka-aloyoga-new-2914427',
 '/products/mayka-aloyoga-new-3034174',
 '/products/yubka-mini-loropiana-pre-owned-5703559',
 '/products/kardigan-celine-new-5711841',
 '/products/yubka-mini-miu-miu-pre-owned-5912560',
 '/products/futbolka-celine-new-4941436',
 '/products/plate-balmain-pre-owned-5174005',
 '/products/trenchplashch-burberry-pre-owned-5882404',
 '/products/trenchplashch-burberry-pre-owned-4919827',
 '/products/khuditolstovka-balenciaga-new-4771225',
 '/products/palto-burberry-pre-owned-5615126',
 '/products/pukhovik-thenorthface-new-4650993',
 '/products/trenchplashch-burberry-pre-owned-5723814',
 '/products/yubka-mini-fendi-pre-owned-4863570',
 '/products/sportivnye-bryuki-i-shorty-fear-of-god-essentials-new-4620570',
 '/products/futbolka-loewe-new-2735888',
 '/products/futbolka-celine-new-4935348',
 '/products/mayka-celine-new-4935295',
 '/products/khuditolstovka-yeezy-new-4875452',
 '/products/pryamye-bryuki-yeezy-new-4771140',
 '/products/rubashka-balenciaga-pre-owned-5919699',
 '/products/dzhemper--sviter-loropiana-pre-owned-3466701',
 '/products/yubka-mini-missoni-pre-owned-3466667',
 '/products/palto-loropiana-pre-owned-3466721',
 '/products/dzhemper--sviter-balenciaga-new-5917819',
 '/products/bodi-wolford-new-5631627',
 '/products/mayka-diesel-new-5839109',
 '/products/longsliv-miu-miu-new-2735476',
 '/products/palto-escada-pre-owned-3616355',
 '/products/zhilet-max-mara-studio-pre-owned-5592005',
 '/products/pryamye-bryuki-gucci-pre-owned-1215892',
 '/products/palto-dolcegabbana-pre-owned-986059',
 '/products/shorty-supreme-new-3366992',
 '/products/trenchplashch-burberry-pre-owned-5725776',
 '/products/pryamye-bryuki-jacquemus-new-2933441',
 '/products/kardigan-dolcegabbana-pre-owned-4771095',
 '/products/futbolka-stussy-new-3362574',
 '/products/pukhovik-burberry-new-2954810',
 '/products/kokteylnoe-plate-burberry-pre-owned-5452588',
 '/products/futbolka-prada-pre-owned-5359600',
 '/products/pukhovik-thenorthface-new-4649724',
 '/products/futbolka-stussy-new-3362103',
 '/products/futbolka-stussy-new-3362105',
 '/products/zhaketpidzhak-celine-new-5236399',
 '/products/futbolka-stussy-new-3887390',
 '/products/dzhemper--sviter-poloralphlauren-new-5089486',
 '/products/futbolka-stussy-new-3366019',
 '/products/futbolka-stussy-new-3366009',
 '/products/povsednevnoe-plate-etro-pre-owned-963621',
 '/products/futbolka-stussy-new-3365966',
 '/products/rubashka-christian-dior-pre-owned-5888768',
 '/products/pukhovik-thenorthface-new-4736010',
 '/products/palto-moncler-pre-owned-5335176',
 '/products/trenchplashch-sonia-rykiel-pre-owned-4898683',
 '/products/futbolka-stussy-new-3365531',
 '/products/sportivnye-bryuki-i-shorty-fear-of-god-essentials-new-4619207',
 '/products/kurtka-iro-pre-owned-5713057',
 '/products/bluzy-marni-pre-owned-5889298',
 '/products/yubka-mini-roberto-cavalli-pre-owned-4542648',
 '/products/trenchplashch-burberry-pre-owned-5620287',
 '/products/zhaketpidzhak-max-mara-studio-pre-owned-1972163',
 '/products/kostyum-s-yubkami-maxmara-pre-owned-5040947',
 '/products/zhaketpidzhak-alexander-mcqueen-new-2941068',
 '/products/futbolka-stella-mccartney-new-5733826',
 '/products/trenchplashch-chanel-pre-owned-4638519',
 '/products/trenchplashch-seebychloe-pre-owned-4149641',
 '/products/trenchplashch-seebychloe-pre-owned-986207',
 '/products/pukhovik-moncler-grenoble-pre-owned-4214880',
 '/products/kurtka-loropiana-pre-owned-4475162',
 '/products/kokteylnoe-plate-alexandre-vauthier-pre-owned-4475233',
 '/products/vechernee-plate-christian-dior-pre-owned-4042481',
 '/products/vechernee-plate-ralphlauren-pre-owned-2808593',
 '/products/vechernee-plate-louis-vuitton-pre-owned-3687937',
 '/products/shuba-gucci-pre-owned-2282562',
 '/products/zhaketpidzhak-gucci-pre-owned-2783927',
 '/products/palto-gucci-new-3801512',
 '/products/kokteylnoe-plate-gucci-new-2671819',
 '/products/vechernee-plate-tom-ford-pre-owned-3136465',
 '/products/dzhinsy-slim-gucci-pre-owned-3684781',
 '/products/kurtka-gucci-pre-owned-2458922',
 '/products/kokteylnoe-plate-gucci-new-5010492',
 '/products/sarafan-for-love-and-lemons-pre-owned-5912325',
 '/products/mayka-for-love-and-lemons-pre-owned-3683670',
 '/products/zhaketpidzhak-dolcegabbana-pre-owned-4034506',
 '/products/plate-by-malene-birger-pre-owned-5912603',
 '/products/povsednevnoe-plate-gucci-pre-owned-5902430',
 '/products/yubka-midi-saintlaurent-pre-owned-3070111',
 '/products/rubashka-dianevonfurstenberg-new-505449',
 '/products/mayka-for-love-and-lemons-pre-owned-3683619',
 '/products/futbolka-saintlaurent-pre-owned-1000056',
 '/products/povsednevnoe-plate-gucci-pre-owned-3648478',
 '/products/yubka-mini-saintlaurent-pre-owned-1408650',
 '/products/dublenka-balenciaga-pre-owned-5705430',
 '/products/dzhemper--sviter-balenciaga-pre-owned-5884620',
 '/products/rubashka-saintlaurent-new-5922348',
 '/products/zhiletka-brunellocucinelli-new-4523557',
 '/products/rubashka-saintlaurent-new-5922345',
 '/products/kardigan-falconeri-new-5833930',
 '/products/vechernee-plate-valentino-pre-owned-5722909',
 '/products/kokteylnoe-plate-christian-dior-pre-owned-3655708',
 '/products/futbolka-brunellocucinelli-new-3733768',
 '/products/futbolka-khaite-new-2766916',
 '/products/yubka-mini-courreges-new-4619393',
 '/products/yubka-maksi-thom-browne-new-4639614',
 '/products/kokteylnoe-plate-dolcegabbana-new-2573024',
 '/products/bluzy-dolcegabbana-new-4798192',
 '/products/pryamye-dzhinsy-mother-new-4086357',
 '/products/kurtka-barbour-new-5304287',
 '/products/mayka-dolcegabbana-new-5190830',
 '/products/kardigan-vivienne-westwood-new-5555186',
 '/products/yubka-mini-thom-browne-new-4020079',
 '/products/pryamye-dzhinsy-agolde-new-3989008',
 '/products/rubashka-sacai-new-5235390',
 '/products/kurtka-fendi-new-2572652',
 '/products/kurtka-loewe-new-5223825',
 '/products/yubka-midi-rick-owens-new-5259462',
 '/products/pryamye-bryuki-brunellocucinelli-new-2927392',
 '/products/futbolka-burberry-new-5008600',
 '/products/pryamye-dzhinsy-r13-new-3802659',
 '/products/futbolka-burberry-new-5061496',
 '/products/futbolka-ami-paris-new-5278211',
 '/products/kardigan-vivienne-westwood-new-5024141',
 '/products/kurtka-ganni-new-3862835',
 '/products/khuditolstovka-sacai-new-5219366',
 '/products/zhaketpidzhak-goldengoosedeluxebrand-new-4697363',
 '/products/khuditolstovka-sacai-new-5287486',
 '/products/khuditolstovka-sacai-new-5235812',
 '/products/khuditolstovka-jacquemus-new-3814292',
 '/products/plate-dolcegabbana-new-4798182',
 '/products/bluzy-goldengoosedeluxebrand-new-3107552',
 '/products/khuditolstovka-dolcegabbana-new-4798181',
 '/products/kardigan-rick-owens-new-4892544',
 '/products/mayka-magda-butrym-new-3655858',
 '/products/bluzy-dolcegabbana-new-5186434',
 '/products/futbolka-moncler-new-5113103',
 '/products/pryamye-bryuki-rick-owens-new-4898085',
 '/products/dzhemper--sviter-sacai-new-5235362',
 '/products/kardigan-vivienne-westwood-new-2849681',
 '/products/zhaketpidzhak-goldengoosedeluxebrand-new-3774015',
 '/products/rubashka-brunellocucinelli-new-2909264',
 '/products/pryamye-dzhinsy-maison-margiela-new-3146274',
 '/products/kardigan-poloralphlauren-new-5438155',
 '/products/dzhemper--sviter-vivienne-westwood-new-2818356',
 '/products/shorty-rick-owens-new-5259415',
 '/products/legginsy-i-velosipedki-marineserre-new-4717420',
 '/products/rubashka-sacai-new-5235810',
 '/products/yubka-midi-sacai-new-5235361',
 '/products/zhaketpidzhak-mm6maisonmargiela-new-2882212',
 '/products/futbolka-sacai-new-5240891',
 '/products/mayka-rick-owens-new-4917849',
 '/products/mayka-rick-owens-new-4892521',
 '/products/plate-dolcegabbana-new-4798150',
 '/products/futbolka-auralee-new-5240856',
 '/products/futbolka-paco-rabanne-new-4798126',
 '/products/pryamye-dzhinsy-maison-margiela-new-2569627',
 '/products/futbolka-dolcegabbana-new-2969046',
 '/products/kurtka-sacai-new-5228776',
 '/products/kurtka-rick-owens-new-5235421',
 '/products/kardigan-poloralphlauren-new-5438107',
 '/products/pryamye-dzhinsy-goldengoosedeluxebrand-new-5228780',
 '/products/rubashka-victoria-beckham-new-4013172',
 '/products/futbolka-off-white-new-2568902',
 '/products/futbolka-off-white-new-2568902',
 '/products/kurtka-courreges-new-4617790',
 '/products/pryamye-dzhinsy-r13-new-2942988',
 '/products/kardigan-sacai-new-5235376',
 '/products/bluzy-lemaire-new-4569860',
 '/products/rubashka-r13-new-3768230',
 '/products/mayka-coperni-new-3218510',
 '/products/kardigan-isabel-marant-etoile-new-2614995',
 '/products/futbolka-khaite-new-2567345',
 '/products/futbolka-jil-sander-new-3592720',
 '/products/kardigan-maison-kitsune-new-5468926',
 '/products/pryamye-bryuki-rick-owens-new-5287345',
 '/products/khuditolstovka-sacai-new-5221187',
 '/products/pryamye-dzhinsy-agolde-new-4011377',
 '/products/rubashka-fendi-new-3054088',
 '/products/bluzy-isabel-marant-new-3075880',
 '/products/mayka-theattico-new-5073983',
 '/products/mayka-dolcegabbana-new-3019488',
 '/products/futbolka-dolcegabbana-new-3120451',
 '/products/dzhinsy-klesh-rick-owens-new-5259395',
 '/products/longsliv-rick-owens-new-5223751',
 '/products/khuditolstovka-sacai-new-5219774',
 '/products/kurtka-rick-owens-new-5287340',
 '/products/kardigan-rick-owens-new-5235336',
 '/products/dzhemper--sviter-fendi-new-2612318',
 '/products/byustgaltery-dolcegabbana-new-2565046',
 '/products/futbolka-auralee-new-5240844',
 '/products/rubashka-poloralphlauren-new-5168368',
 '/products/rubashka-dolcegabbana-new-5194498',
 '/products/pryamye-bryuki-brunellocucinelli-new-4732805',
 '/products/zhaketpidzhak-dolcegabbana-new-4798011',
 '/products/povsednevnoe-plate-sacai-new-5287315',
 '/products/yubka-mini-dolcegabbana-new-4798017',
 '/products/pryamye-dzhinsy-goldengoosedeluxebrand-new-5468818',
 '/products/dzhemper--sviter-poloralphlauren-new-5438135',
 '/products/dzhemper--sviter-poloralphlauren-new-4009581',
 '/products/pryamye-bryuki-rick-owens-new-5287382',
 '/products/bluzy-coperni-new-3059605',
 '/products/povsednevnoe-plate-isabel-marant-etoile-new-5237149',
 '/products/plate-rotate-new-5143938',
 '/products/korset-saintlaurent-pre-owned-3361492',
 '/products/mayka-aloyoga-new-5348722',
 '/products/povsednevnoe-plate-chanel-pre-owned-4580438',
 '/products/futbolka-pinko-pre-owned-1128728',
 '/products/khuditolstovka-valentino-new-5225442',
 '/products/dzhinsy-klesh-calvin-klein-new-2156738',
 '/products/futbolka-balenciaga-new-5897652',
 '/products/futbolka-balenciaga-new-5897663',
 '/products/vodolazka-wolford-new-5921555',
 '/products/dzhemper--sviter-courreges-new-5897619',
 '/products/mayka-wolford-new-5921556',
 '/products/vodolazka-wolford-new-5921558',
 '/products/bodi-wolford-new-5572296',
 '/products/bodi-wolford-new-5921559',
 '/products/bodi-wolford-new-5921568',
 '/products/futbolka-alexander-wang-new-5866838',
 '/products/byustgaltery-blugirl-new-5363007',
 '/products/pryamye-dzhinsy-victoria-beckham-pre-owned-852443',
 '/products/kokteylnoe-plate-versace-pre-owned-3158819',
 '/products/mayka-victoria-beckham-pre-owned-1905081',
 '/products/yubka-midi-versace-collection-pre-owned-4542581',
 '/products/kokteylnoe-plate-juicy-couture-pre-owned-4849402',
 '/products/yubka-mini-victoria-beckham-pre-owned-741606',
 '/products/futbolka-maxmara-new-5915188',
 '/products/dzhinsy-klesh-victoria-beckham-pre-owned-3227057',
 '/products/dzhinsy-slim-victoria-beckham-pre-owned-723021',
 '/products/povsednevnoe-plate-blumarine-pre-owned-4710971',
 '/products/futbolka-s-max-mara-new-5916375',
 '/products/povsednevnoe-plate-victoria-beckham-new-3233312',
 '/products/dublenka-yves-salomon-pre-owned-4945810',
 '/products/pryamye-bryuki-s-max-mara-new-5916385',
 '/products/povsednevnoe-plate-404notfound-pre-owned-4345181',
 '/products/bryuki-shirokie-s-max-mara-new-5916393',
 '/products/povsednevnoe-plate-wolford-pre-owned-5907148',
 '/products/vechernee-plate-dolcegabbana-pre-owned-2092285',
 '/products/mayka-tom-ford-new-5886840',
 '/products/kardigan-maxmara-new-5915120',
 '/products/futbolka-loewe-new-5922899',
 '/products/kurtka-harleydavidson-pre-owned-5398877',
 '/products/dzhemper--sviter-red-valentino-pre-owned-5276481',
 '/products/kardigan-maxmara-new-5915286',
 '/products/zhaketpidzhak-chanel-pre-owned-5533426',
 '/products/kokteylnoe-plate-twin-set-new-5613598',
 '/products/yubka-midi-brunellocucinelli-pre-owned-5335266',
 '/products/yubka-midi-celine-pre-owned-5385425',
 '/products/bryuki-shirokie-comme-des-garons-pre-owned-5291402',
 '/products/kurtka-balmain-pre-owned-459682',
 '/products/pryamye-dzhinsy-jacob-cohen-new-5292630',
 '/products/bryuki-shirokie-emilio-pucci-pre-owned-5385436',
 '/products/bluzy-isabel-marant-etoile-pre-owned-5331112',
 '/products/bryuki-shirokie-saintlaurent-pre-owned-5292818',
 '/products/dzhemper--sviter-chanel-pre-owned-898549',
 '/products/bryuki-shirokie-emilio-pucci-pre-owned-5291419',
 '/products/rubashka-zimmermann-new-5887950',
 '/products/dzhemper--sviter-balenciaga-pre-owned-5445832',
 '/products/pryamye-dzhinsy-darkpark-new-5867530',
 '/products/futbolka-christian-dior-pre-owned-4154034',
 '/products/kurtka-sandro-pre-owned-2695565',
 '/products/povsednevnoe-plate-fendi-new-5913667',
 '/products/shorty-sandro-new-3449431',
 '/products/palto-brunellocucinelli-new-5913661',
 '/products/bluzy-pinko-new-3488740',
 '/products/kurtka-saintlaurent-pre-owned-4193436',
 '/products/rubashka-thefrankieshop-new-5915951',
 '/products/futbolka-miu-miu-pre-owned-5922329',
 '/products/yubka-midi-etro-pre-owned-644589',
 '/products/kupalnik-eres-new-4243326',
 '/products/dzhemper--sviter-balmain-pre-owned-5329955',
 '/products/pryamye-dzhinsy-armanijeans-pre-owned-621043',
 '/products/zhaketpidzhak-mcq-alexander-mcqueen-pre-owned-3566513',
 '/products/dzhemper--sviter-dolcegabbana-pre-owned-1461943',
 '/products/palto-sportmax-pre-owned-1455396',
 '/products/yubka-mini-theory-pre-owned-498779',
 '/products/dzhemper--sviter-chloe-pre-owned-2554709',
 '/products/shorty-zimmermann-pre-owned-3759265',
 '/products/yubka-mini-isabel-marant-etoile-pre-owned-2358899',
 '/products/dzhemper--sviter-balenciaga-pre-owned-5516722',
 '/products/khuditolstovka-gucci-pre-owned-5850462',
 '/products/mayka-zimmermann-new-1877496',
 '/products/pukhovik-nanushka-pre-owned-1053978',
 '/products/dzhemper--sviter-vetements-pre-owned-5850441',
 '/products/bluzy-isabel-marant-pre-owned-1131099',
 '/products/dzhinsy-klesh-loulou-studio-pre-owned-1718923',
 '/products/dzhemper--sviter-loewe-new-1718995',
 '/products/bryuki-uzkie-maxmara-pre-owned-1779181',
 '/products/dzhemper--sviter-joseph-pre-owned-5207813',
 '/products/yubka-midi-valentino-new-5899362',
 '/products/dzhemper--sviter-equipment-pre-owned-5257568',
 '/products/palto-dianevonfurstenberg-pre-owned-5567318',
 '/products/dzhemper--sviter-jil-sander-pre-owned-1295210',
 '/products/yubka-mini-isabel-marant-etoile-pre-owned-560255',
 '/products/shorty-forte-couture-pre-owned-3951140',
 '/products/shorty-120-lino-pre-owned-5725004',
 '/products/longsliv-skims-new-5858959',
 '/products/kupalnik-diesel-new-5913048',
 '/products/plate-michaelkors-pre-owned-5691475',
 '/products/povsednevnoe-plate-isabel-marant-etoile-new-502663',
 '/products/futbolka-versace-pre-owned-1210818',
 '/products/plate-lanvin-pre-owned-5630873',
 '/products/futbolka-fendi-new-5915202',
 '/products/pryamye-bryuki-loulou-de-saison-pre-owned-4406820',
 '/products/dzhemper--sviter-toteme-new-2736599',
 '/products/povsednevnoe-plate-burberry-pre-owned-498768',
 '/products/kokteylnoe-plate-off-white-pre-owned-3085582',
 '/products/rubashka-etro-pre-owned-2247940',
 '/products/futbolka-balenciaga-pre-owned-5636051',
 '/products/yubka-midi-max-mara-studio-pre-owned-715142',
 '/products/palto-weekendmaxmara-pre-owned-5566927',
 '/products/kokteylnoe-plate-christopher-esber-pre-owned-5636098',
 '/products/povsednevnoe-plate-louis-vuitton-pre-owned-5517107',
 '/products/korset-versace-pre-owned-3159843',
 '/products/yubka-midi-blumarine-pre-owned-4047772',
 '/products/bluzy-self-portrait-pre-owned-5424430',
 '/products/yubka-mini-alaia-pre-owned-5922541',
 '/products/kostyum-s-yubkami-diesel-new-5922515',
 '/products/dzhemper--sviter-maje-pre-owned-508244',
 '/products/povsednevnoe-plate-zimmermann-pre-owned-5920111',
 '/products/zhaketpidzhak-chanel-pre-owned-1387586',
 '/products/khuditolstovka-heronpreston-pre-owned-5643418',
 '/products/yubka-mini-prada-new-5912893',
 '/products/povsednevnoe-plate-oseree-new-5707815',
 '/products/futbolka-fendi-new-5910648',
 '/products/plate-oseree-new-5707619',
 '/products/kupalnik-oseree-new-5323470',
 '/products/bluzy-oseree-new-5616196',
 '/products/rubashka-oseree-new-5707752',
 '/products/rubashka-oseree-new-5707753',
 '/products/rubashka-alaia-new-5921183',
 '/products/pryamye-dzhinsy-balenciaga-pre-owned-5864890',
 '/products/povsednevnoe-plate-alaia-new-5921180',
 '/products/kokteylnoe-plate-alaia-new-5921186',
 '/products/zhaketpidzhak-balmain-pre-owned-5899273',
 '/products/futbolka-moschino-new-5779003',
 '/products/khuditolstovka-mm6maisonmargiela-new-5778887',
 '/products/futbolka-moschino-new-5778472',
 '/products/futbolka-ps-by-paul-smith-new-5778530',
 '/products/futbolka-moschino-new-5778538',
 '/products/futbolka-comme-des-garons-play-new-5778668',
 '/products/futbolka-moschino-new-5778587',
 '/products/futbolka-moschino-new-5778596',
 '/products/futbolka-moschino-new-5778480',
 '/products/khuditolstovka-dolcegabbana-new-5922096',
 '/products/sportivnye-bryuki-i-shorty-dolcegabbana-new-5922126',
 '/products/futbolka-gucci-new-5922147',
 '/products/futbolka-moschino-new-5777367',
 '/products/bluzy-miu-miu-pre-owned-5921711',
 '/products/khuditolstovka-rotate-new-5777596',
 '/products/bluzy-chloe-pre-owned-2061450',
 '/products/futbolka-moschino-new-5777213',
 '/products/kokteylnoe-plate-alexander-mcqueen-pre-owned-5921844',
 '/products/kokteylnoe-plate-giorgio-armani-pre-owned-652112',
 '/products/shorty-alexander-wang-pre-owned-5922218',
 '/products/povsednevnoe-plate-jacquemus-pre-owned-5831276',
 '/products/zhaketpidzhak-gucci-pre-owned-5922114',
 '/products/futbolka-celine-pre-owned-5663655',
 '/products/sarafan-roberto-cavalli-pre-owned-5922480',
 '/products/futbolka-chanel-pre-owned-5922414',
 '/products/povsednevnoe-plate-dries-van-noten-pre-owned-2229720',
 '/products/futbolka-coperni-new-5776001',
 '/products/pryamye-bryuki-tom-ford-pre-owned-5892517',
 '/products/bryuki-uzkie-prada-pre-owned-5884585',
 '/products/rubashka-loropiana-pre-owned-5912748',

In [ ]:
for i in range(1, 101):
  url = 'https://oskelly.ru/catalog/muzhskoe/odezhda?page=' + str(i)
  oskelly = requests.get(url, headers=headers)
  soup = BeautifulSoup(oskelly.text, 'html')
  page = soup.find_all("a", class_="osk-product-card__card-img")
  for elem in page:
    items.append(elem.get('href'))
  time.sleep(1)

In [ ]:
pd.Series(items).to_excel('links200.xlsx', index=False)

In [ ]:
len(items)

9600

In [ ]:
# url = 'https://oskelly.ru/products/khuditolstovka-burberry-pre-owned-5634296'
# oskelly = requests.get(url, headers=headers)
# soup = BeautifulSoup(oskelly.text, 'html')
# soup.find_all('li')

In [ ]:
# for elem in soup.find_all('li'):
#   print(elem.text)

In [ ]:
# url = 'https://oskelly.ru/products/futbolka-balenciaga-new-3096433'
# oskelly = requests.get(url, headers=headers)
# soup = BeautifulSoup(oskelly.text, 'html')
# soup.find_all('li')

In [ ]:
# for elem in soup.find_all('li'):
#   print(elem.text)

In [ ]:
# item = {}
# for elem in soup.find_all('li', class_='osk-product-attributes__item'):
#     name = elem.find('span', class_='osk-product-attributes__item-name').text.strip()
#     value = elem.find('span', class_='osk-product-attributes__item-value').text.strip()
#     item[name] = value
# item

In [ ]:
# soup.find('span', class_='osk-product__rrpPrice').text.replace('\xa0', '').replace('₽', '')

In [ ]:
# soup.find('span', class_='osk-product__discount').text

In [ ]:
items = pd.read_excel('links200.xlsx')

In [ ]:
# items.iloc[0, 0]

In [ ]:
# url = 'https://oskelly.ru'+items.iloc[0, 0]
# oskelly = requests.get(url, headers=headers)
# soup = BeautifulSoup(oskelly.text, 'html')
# soup.find('div', class_='osk-product-seller__description').text

In [ ]:
all_items = []

for i in range(0, 100):
  url = 'https://oskelly.ru' + items.iloc[i, 0]
  oskelly = requests.get(url, headers=headers)

  if oskelly.status_code == 200:
    soup = BeautifulSoup(oskelly.text, 'html')
    item = {}

    item_id = items.iloc[i, 0].split('-')[-1]
    item['Oskelly ID'] = item_id
    item['url'] = url

    for elem in soup.find_all('li', class_='osk-product-attributes__item'):
      name_elem = elem.find('span', class_='osk-product-attributes__item-name')
      value_elem = elem.find('span', class_='osk-product-attributes__item-value')

      if name_elem and value_elem:
        category = name_elem.text.strip()
        value = value_elem.text.strip()
        item[category] = value

    price = soup.find('span', class_='osk-product__rrpPrice')
    if price:
      item['Цена'] = price.text.replace('\xa0', '').replace('₽', '').strip()

    discount = soup.find('span', class_='osk-product__discount')
    if discount:
      item['Скидка'] = discount.text.strip()

    price2 = soup.find('span', class_='osk-product__price')
    if price2 and 'Цена' not in item:
      item['Цена'] = price2.text.replace('\xa0', '').replace('₽', '').strip()


    description = soup.find('div', class_='osk-product-seller__description')
    if description:
      item['Описание'] = description.text.strip()


    brand = soup.find('a', class_='osk-product__brand')
    if brand:
      item['Бренд'] = brand.text.strip()


    title = soup.find('h1', class_='osk-product__title')
    if title:
      item['Название'] = title.text.strip()


    condition = soup.find('div', class_='osk-product__condition')
    if condition:
      item['Состояние'] = condition.text.strip()


    image_url = get_main_product_image_url(soup)
    image_path = download_main_product_image(image_url=image_url,item_id=item_id,images_dir=images_dir)

    item['image_url'] = image_url
    item['image_path'] = image_path

    all_items.append(item)

    print(item_id, item.get('Бренд'), item.get('Цена'), image_path)

  time.sleep(0.5)

5272379 MIU MIU 110701 /content/udrive/MyDrive/GP5/oskelly_images/5272379.jpg
5914800 CHRISTIAN DIOR 31000 /content/udrive/MyDrive/GP5/oskelly_images/5914800.jpg
4201550 BURBERRY 195354 /content/udrive/MyDrive/GP5/oskelly_images/4201550.jpg
5146377 ALO YOGA 13510 /content/udrive/MyDrive/GP5/oskelly_images/5146377.jpg
5271514 ALO YOGA 15960 /content/udrive/MyDrive/GP5/oskelly_images/5271514.jpg
4855327 ALO YOGA 29840 /content/udrive/MyDrive/GP5/oskelly_images/4855327.jpg
3790125 ACNE STUDIOS 35910 /content/udrive/MyDrive/GP5/oskelly_images/3790125.jpg
3684331 STUSSY 12930 /content/udrive/MyDrive/GP5/oskelly_images/3684331.jpg
3664015 ACNE STUDIOS 30171 /content/udrive/MyDrive/GP5/oskelly_images/3664015.jpg
5582336 ACNE STUDIOS 37200 /content/udrive/MyDrive/GP5/oskelly_images/5582336.jpg
3369121 ACNE STUDIOS 32559 /content/udrive/MyDrive/GP5/oskelly_images/3369121.jpg
3896276 ACNE STUDIOS 26640 /content/udrive/MyDrive/GP5/oskelly_images/3896276.jpg
5848065 BARBOUR 501788 /content/udrive/MyDrive/GP5/oskelly_images/5848065.jpg
2009924 PIERRE BALMAIN 21000 /content/udrive/MyDrive/GP5/oskelly_images/2009924.jpg
3645389 ALAIA 116616 /content/udrive/MyDrive/GP5/oskelly_images/3645389.jpg
4777181 GOLDEN GOOSE 180784 /content/udrive/MyDrive/GP5/oskelly_images/4777181.jpg
4766815 GIVENCHY 52447 /content/udrive/MyDrive/GP5/oskelly_images/4766815.jpg
5062231 POLO RALPH LAUREN 25559 /content/udrive/MyDrive/GP5/oskelly_images/5062231.jpg
5914552 BURBERRY 100150 /content/udrive/MyDrive/GP5/oskelly_images/5914552.jpg
3364573 STUSSY 35530 /content/udrive/MyDrive/GP5/oskelly_images/3364573.jpg
3368630 ACNE STUDIOS 26640 /content/udrive/MyDrive/GP5/oskelly_images/3368630.jpg
3368506 ACNE STUDIOS 26660 /content/udrive/MyDrive/GP5/oskelly_images/3368506.jpg
3694600 ACNE STUDIOS 17170 /content/udrive/MyDrive/GP5/oskelly_images/3694600.jpg
3368321 ACNE STUDIOS 64740 /content/udrive/MyDrive/GP5/oskelly_images/3368321.jpeg
3368150 ACNE STUDIOS 28420 /content/udrive/MyDrive/GP5/oskelly_images/3368150.jpg
3425404 LOEWE 50050 /content/udrive/MyDrive/GP5/oskelly_images/3425404.jpg
2906017 ALO YOGA 14700 /content/udrive/MyDrive/GP5/oskelly_images/2906017.jpg
3090070 ALO YOGA 11560 /content/udrive/MyDrive/GP5/oskelly_images/3090070.jpg
5270527 ALO YOGA 11400 /content/udrive/MyDrive/GP5/oskelly_images/5270527.jpg
5429015 ALO YOGA 18810 /content/udrive/MyDrive/GP5/oskelly_images/5429015.jpg
2914427 ALO YOGA 24860 /content/udrive/MyDrive/GP5/oskelly_images/2914427.jpg
3034174 ALO YOGA 14700 /content/udrive/MyDrive/GP5/oskelly_images/3034174.jpg
5703559 LORO PIANA 50000 /content/udrive/MyDrive/GP5/oskelly_images/5703559.jpg
5711841 CELINE 338169 /content/udrive/MyDrive/GP5/oskelly_images/5711841.jpeg
5912560 MIU MIU 82500 /content/udrive/MyDrive/GP5/oskelly_images/5912560.jpg
4941436 CELINE 48710 /content/udrive/MyDrive/GP5/oskelly_images/4941436.jpg
5174005 BALMAIN 85500 /content/udrive/MyDrive/GP5/oskelly_images/5174005.jpg
5882404 BURBERRY 480000 /content/udrive/MyDrive/GP5/oskelly_images/5882404.jpg
4919827 BURBERRY 150000 /content/udrive/MyDrive/GP5/oskelly_images/4919827.jpg
4771225 BALENCIAGA 83568 /content/udrive/MyDrive/GP5/oskelly_images/4771225.jpg
5615126 BURBERRY 29000 /content/udrive/MyDrive/GP5/oskelly_images/5615126.jpg
4650993 THE NORTH FACE 28420 /content/udrive/MyDrive/GP5/oskelly_images/4650993.jpg
5723814 BURBERRY 29000 /content/udrive/MyDrive/GP5/oskelly_images/5723814.jpg
4863570 FENDI 54000 /content/udrive/MyDrive/GP5/oskelly_images/4863570.jpg
4620570 FEAR OF GOD ESSENTIALS 11400 /content/udrive/MyDrive/GP5/oskelly_images/4620570.jpg
2735888 LOEWE 83440 /content/udrive/MyDrive/GP5/oskelly_images/2735888.jpg
4935348 CELINE 51552 /content/udrive/MyDrive/GP5/oskelly_images/4935348.jpg
4935295 CELINE 55350 /content/udrive/MyDrive/GP5/oskelly_images/4935295.jpg
4875452 YEEZY 13510 /content/udrive/MyDrive/GP5/oskelly_images/4875452.jpg
4771140 YEEZY 11230 /content/udrive/MyDrive/GP5/oskelly_images/4771140.jpeg
5919699 BALENCIAGA 120000 /content/udrive/MyDrive/GP5/oskelly_images/5919699.jpg
3466701 LORO PIANA 67000 /content/udrive/MyDrive/GP5/oskelly_images/3466701.jpg
3466667 MISSONI 78000 /content/udrive/MyDrive/GP5/oskelly_images/3466667.jpg
3466721 LORO PIANA 160000 /content/udrive/MyDrive/GP5/oskelly_images/3466721.jpg
5917819 BALENCIAGA 130000 /content/udrive/MyDrive/GP5/oskelly_images/5917819.jpg
5631627 WOLFORD 15000 /content/udrive/MyDrive/GP5/oskelly_images/5631627.jpeg
5839109 DIESEL 38000 /content/udrive/MyDrive/GP5/oskelly_images/5839109.jpg
2735476 MIU MIU 73800 /content/udrive/MyDrive/GP5/oskelly_images/2735476.jpg
3616355 ESCADA 128000 /content/udrive/MyDrive/GP5/oskelly_images/3616355.jpg
5592005 MAX MARA STUDIO 45000 /content/udrive/MyDrive/GP5/oskelly_images/5592005.jpg
1215892 GUCCI 65000 /content/udrive/MyDrive/GP5/oskelly_images/1215892.jpg
986059 DOLCE&GABBANA 480000 /content/udrive/MyDrive/GP5/oskelly_images/986059.jpg
3366992 SUPREME 22900 /content/udrive/MyDrive/GP5/oskelly_images/3366992.jpg
5725776 BURBERRY 39000 /content/udrive/MyDrive/GP5/oskelly_images/5725776.jpg
2933441 JACQUEMUS 50293 /content/udrive/MyDrive/GP5/oskelly_images/2933441.jpg
4771095 DOLCE&GABBANA 43650 /content/udrive/MyDrive/GP5/oskelly_images/4771095.jpg
3362574 STUSSY 15070 /content/udrive/MyDrive/GP5/oskelly_images/3362574.jpg
2954810 BURBERRY 160624 /content/udrive/MyDrive/GP5/oskelly_images/2954810.jpg
5452588 BURBERRY 140000 /content/udrive/MyDrive/GP5/oskelly_images/5452588.jpg
5359600 PRADA 26000 /content/udrive/MyDrive/GP5/oskelly_images/5359600.jpg
4649724 THE NORTH FACE 26210 /content/udrive/MyDrive/GP5/oskelly_images/4649724.jpg
3362103 STUSSY 13010 /content/udrive/MyDrive/GP5/oskelly_images/3362103.jpg
3362105 STUSSY 11630 /content/udrive/MyDrive/GP5/oskelly_images/3362105.jpg
5236399 CELINE 267369 /content/udrive/MyDrive/GP5/oskelly_images/5236399.jpeg
3887390 STUSSY 14700 /content/udrive/MyDrive/GP5/oskelly_images/3887390.jpg
5089486 POLO RALPH LAUREN 18810 /content/udrive/MyDrive/GP5/oskelly_images/5089486.jpg
3366019 STUSSY 11400 /content/udrive/MyDrive/GP5/oskelly_images/3366019.jpg
3366009 STUSSY 15960 /content/udrive/MyDrive/GP5/oskelly_images/3366009.jpg
963621 ETRO 90000 /content/udrive/MyDrive/GP5/oskelly_images/963621.jpg
3365966 STUSSY 10790 /content/udrive/MyDrive/GP5/oskelly_images/3365966.jpg
5888768 CHRISTIAN DIOR 49000 /content/udrive/MyDrive/GP5/oskelly_images/5888768.jpg
4736010 THE NORTH FACE 35520 /content/udrive/MyDrive/GP5/oskelly_images/4736010.jpg
5335176 MONCLER 90000 /content/udrive/MyDrive/GP5/oskelly_images/5335176.jpg
4898683 SONIA RYKIEL 105000 /content/udrive/MyDrive/GP5/oskelly_images/4898683.jpg
3365531 STUSSY 12720 /content/udrive/MyDrive/GP5/oskelly_images/3365531.jpg
4619207 FEAR OF GOD ESSENTIALS 24860 /content/udrive/MyDrive/GP5/oskelly_images/4619207.jpeg
5713057 IRO 19000 /content/udrive/MyDrive/GP5/oskelly_images/5713057.jpg
5889298 MARNI 12000 /content/udrive/MyDrive/GP5/oskelly_images/5889298.jpg
4542648 ROBERTO CAVALLI 110000 /content/udrive/MyDrive/GP5/oskelly_images/4542648.jpg
5620287 BURBERRY 250000 /content/udrive/MyDrive/GP5/oskelly_images/5620287.jpg
1972163 MAX MARA STUDIO 35000 /content/udrive/MyDrive/GP5/oskelly_images/1972163.jpg
5040947 MAX MARA 18000 /content/udrive/MyDrive/GP5/oskelly_images/5040947.jpg
2941068 ALEXANDER MCQUEEN 111000 /content/udrive/MyDrive/GP5/oskelly_images/2941068.jpg
5733826 STELLA MCCARTNEY 14290 /content/udrive/MyDrive/GP5/oskelly_images/5733826.jpg
4638519 CHANEL 700000 /content/udrive/MyDrive/GP5/oskelly_images/4638519.jpg
4149641 SEE BY CHLOE 72000 /content/udrive/MyDrive/GP5/oskelly_images/4149641.jpg
986207 SEE BY CHLOE 51000 /content/udrive/MyDrive/GP5/oskelly_images/986207.jpg
4214880 MONCLER GRENOBLE 185000 /content/udrive/MyDrive/GP5/oskelly_images/4214880.jpg
4475162 LORO PIANA 90000 /content/udrive/MyDrive/GP5/oskelly_images/4475162.jpeg
4475233 ALEXANDRE VAUTHIER 35000 /content/udrive/MyDrive/GP5/oskelly_images/4475233.jpeg

In [ ]:
data = pd.DataFrame(all_items)
data.to_excel('all_items_100_with_images.xlsx', index=False)
data.head()

,Oskelly ID,url,Размер,Раздел,Категория,Бренд,Материал одежды,Цвет,Состояние товара,Продавец,Цена,Скидка,Описание,Название,Состояние,image_url,image_path,Посадка,Материал джинсов,Винтаж
0,5272379,https://oskelly.ru/products/rubashka-miu-miu-n...,IT 40,Женское,Рубашки,MIU MIU,Другое,Зеленый,Новое с биркой,Бутик,110701,-31%,MIU MIU Shirts Women's Dark Green Moderate\n\n...,MIU MIUЗеленая рубашкаЗеленая рубашка,Новое с биркой,https://static.cdn.oskelly.ru/product/5272379/...,/content/udrive/MyDrive/GP5/oskelly_images/527...,NaN,NaN,NaN
1,5914800,https://oskelly.ru/products/kupalnik-christian...,FR 36,Женское,Купальники,CHRISTIAN DIOR,Другое,Синий,Новое с биркой,Частный продавец,31000,-11%,"Новый маркировка 36,смотрите пожалуйста внимат...",CHRISTIAN DIORСиний купальникСиний купальник,Новое с биркой,https://static.cdn.oskelly.ru/product/5914800/...,/content/udrive/MyDrive/GP5/oskelly_images/591...,NaN,NaN,NaN
2,4201550,https://oskelly.ru/products/trenchplashch-burb...,UK 10/12,Женское,Тренчи и плащи,BURBERRY,Другое,Розовый,Новое с биркой,Бутик,195354,-81%,Burberry Trench Coats Women's Pink\n\n • Pink\...,BURBERRYРозовый тренч/плащРозовый тренч/плащ,Новое с биркой,https://static.cdn.oskelly.ru/product/4201550/...,/content/udrive/MyDrive/GP5/oskelly_images/420...,NaN,NaN,NaN
3,5146377,https://oskelly.ru/products/sportivnye-bryuki-...,INT 2XS/XS,Женское,Спортивные брюки и шорты,ALO YOGA,Другое,Желтый,Новое с биркой,Бутик,13510,NaN,Alo Yoga Accolade Sports Shorts Women's\n\n • ...,ALO YOGAЖелтые спортивные брюки и шортыЖелтые ...,Новое с биркой,https://static.cdn.oskelly.ru/product/5146377/...,/content/udrive/MyDrive/GP5/oskelly_images/514...,NaN,NaN,NaN
4,5271514,https://oskelly.ru/products/mayka-aloyoga-new-...,INT S/M,Женское,Майки,ALO YOGA,Другое,Розовый,Новое с биркой,Бутик,15960,-15%,Alo Yoga Tank Tops Women's U neck Moderate Oth...,ALO YOGAРозовая майкаРозовая майка,Новое с биркой,https://static.cdn.oskelly.ru/product/5271514/...,/content/udrive/MyDrive/GP5/oskelly_images/527...,NaN,NaN,NaN

In [ ]:
#data[['Oskelly ID', 'Бренд', 'Цена', 'image_url', 'image_path']].head(10)

,Oskelly ID,Бренд,Цена,image_url,image_path
0,5272379,MIU MIU,110701,https://static.cdn.oskelly.ru/product/5272379/...,/content/udrive/MyDrive/GP5/oskelly_images/527...
1,5914800,CHRISTIAN DIOR,31000,https://static.cdn.oskelly.ru/product/5914800/...,/content/udrive/MyDrive/GP5/oskelly_images/591...
2,4201550,BURBERRY,195354,https://static.cdn.oskelly.ru/product/4201550/...,/content/udrive/MyDrive/GP5/oskelly_images/420...
3,5146377,ALO YOGA,13510,https://static.cdn.oskelly.ru/product/5146377/...,/content/udrive/MyDrive/GP5/oskelly_images/514...
4,5271514,ALO YOGA,15960,https://static.cdn.oskelly.ru/product/5271514/...,/content/udrive/MyDrive/GP5/oskelly_images/527...
5,4855327,ALO YOGA,29840,https://static.cdn.oskelly.ru/product/4855327/...,/content/udrive/MyDrive/GP5/oskelly_images/485...
6,3790125,ACNE STUDIOS,35910,https://static.cdn.oskelly.ru/product/3790125/...,/content/udrive/MyDrive/GP5/oskelly_images/379...
7,3684331,STUSSY,12930,https://static.cdn.oskelly.ru/product/3684331/...,/content/udrive/MyDrive/GP5/oskelly_images/368...
8,3664015,ACNE STUDIOS,30171,https://static.cdn.oskelly.ru/product/3664015/...,/content/udrive/MyDrive/GP5/oskelly_images/366...
9,5582336,ACNE STUDIOS,37200,https://static.cdn.oskelly.ru/product/5582336/...,/content/udrive/MyDrive/GP5/oskelly_images/558...

In [ ]:
# url = 'https://oskelly.ru'+items.iloc[0, 0]
# oskelly = requests.get(url, headers=headers)
# type(oskelly.status_code)

In [ ]:
all_items = []

for i in range(100, 200):
  url = 'https://oskelly.ru' + items.iloc[i, 0]
  oskelly = requests.get(url, headers=headers)

  if oskelly.status_code == 200:
    soup = BeautifulSoup(oskelly.text, 'html')
    item = {}

    item_id = items.iloc[i, 0].split('-')[-1]
    item['Oskelly ID'] = item_id
    item['url'] = url

    for elem in soup.find_all('li', class_='osk-product-attributes__item'):
      name_elem = elem.find('span', class_='osk-product-attributes__item-name')
      value_elem = elem.find('span', class_='osk-product-attributes__item-value')

      if name_elem and value_elem:
        category = name_elem.text.strip()
        value = value_elem.text.strip()
        item[category] = value

    price = soup.find('span', class_='osk-product__rrpPrice')
    if price:
      item['Цена'] = price.text.replace('\xa0', '').replace('₽', '').strip()

    discount = soup.find('span', class_='osk-product__discount')
    if discount:
      item['Скидка'] = discount.text.strip()

    price2 = soup.find('span', class_='osk-product__price')
    if price2 and 'Цена' not in item:
      item['Цена'] = price2.text.replace('\xa0', '').replace('₽', '').strip()


    description = soup.find('div', class_='osk-product-seller__description')
    if description:
      item['Описание'] = description.text.strip()


    brand = soup.find('a', class_='osk-product__brand')
    if brand:
      item['Бренд'] = brand.text.strip()


    title = soup.find('h1', class_='osk-product__title')
    if title:
      item['Название'] = title.text.strip()


    condition = soup.find('div', class_='osk-product__condition')
    if condition:
      item['Состояние'] = condition.text.strip()


    image_url = get_main_product_image_url(soup)
    image_path = download_main_product_image(image_url=image_url,item_id=item_id,images_dir=images_dir)

    item['image_url'] = image_url
    item['image_path'] = image_path

    all_items.append(item)

    print(item_id, item.get('Бренд'), item.get('Цена'), image_path)

  time.sleep(0.5)

4042481 CHRISTIAN DIOR 1200000 /content/udrive/MyDrive/GP5/oskelly_images/4042481.jpg
2808593 RALPH LAUREN 3600000 /content/udrive/MyDrive/GP5/oskelly_images/2808593.jpg
3687937 LOUIS VUITTON 637000 /content/udrive/MyDrive/GP5/oskelly_images/3687937.jpg
2282562 GUCCI 9640000 /content/udrive/MyDrive/GP5/oskelly_images/2282562.jpg
2783927 GUCCI 978000 /content/udrive/MyDrive/GP5/oskelly_images/2783927.jpg
3801512 GUCCI 1500000 /content/udrive/MyDrive/GP5/oskelly_images/3801512.jpg
2671819 GUCCI 208960 /content/udrive/MyDrive/GP5/oskelly_images/2671819.jpg
3136465 TOM FORD 591000 /content/udrive/MyDrive/GP5/oskelly_images/3136465.jpg
3684781 GUCCI 85000 /content/udrive/MyDrive/GP5/oskelly_images/3684781.jpg
2458922 GUCCI 357900 /content/udrive/MyDrive/GP5/oskelly_images/2458922.jpg
5010492 GUCCI 355000 /content/udrive/MyDrive/GP5/oskelly_images/5010492.jpg
5912325 FOR LOVE AND LEMONS 57000 /content/udrive/MyDrive/GP5/oskelly_images/5912325.jpg
3683670 FOR LOVE AND LEMONS 17000 /content/udrive/MyDrive/GP5/oskelly_images/3683670.jpg
4034506 DOLCE&GABBANA 1048950 /content/udrive/MyDrive/GP5/oskelly_images/4034506.jpg
5912603 BY MALENE BIRGER 55000 /content/udrive/MyDrive/GP5/oskelly_images/5912603.jpg
5902430 GUCCI 50000 /content/udrive/MyDrive/GP5/oskelly_images/5902430.jpg
3070111 SAINT LAURENT 530000 /content/udrive/MyDrive/GP5/oskelly_images/3070111.jpg
505449 DIANE VON FURSTENBERG 16000 /content/udrive/MyDrive/GP5/oskelly_images/505449.jpg
3683619 FOR LOVE AND LEMONS 16000 /content/udrive/MyDrive/GP5/oskelly_images/3683619.jpg
1000056 SAINT LAURENT 32000 /content/udrive/MyDrive/GP5/oskelly_images/1000056.jpg
3648478 GUCCI 525000 /content/udrive/MyDrive/GP5/oskelly_images/3648478.jpg
1408650 SAINT LAURENT 30000 /content/udrive/MyDrive/GP5/oskelly_images/1408650.jpg
5705430 BALENCIAGA 350000 /content/udrive/MyDrive/GP5/oskelly_images/5705430.jpg
5884620 BALENCIAGA 100000 /content/udrive/MyDrive/GP5/oskelly_images/5884620.jpeg
5922348 SAINT LAURENT 133727 /content/udrive/MyDrive/GP5/oskelly_images/5922348.jpeg
4523557 BRUNELLO CUCINELLI 118000 /content/udrive/MyDrive/GP5/oskelly_images/4523557.jpg
5922345 SAINT LAURENT 203201 /content/udrive/MyDrive/GP5/oskelly_images/5922345.jpeg
5833930 FALCONERI 21900 /content/udrive/MyDrive/GP5/oskelly_images/5833930.jpeg
5722909 VALENTINO 24000 /content/udrive/MyDrive/GP5/oskelly_images/5722909.jpg
3655708 CHRISTIAN DIOR 450000 /content/udrive/MyDrive/GP5/oskelly_images/3655708.jpg
3733768 BRUNELLO CUCINELLI 58864 /content/udrive/MyDrive/GP5/oskelly_images/3733768.jpg
2766916 KHAITE 31058 /content/udrive/MyDrive/GP5/oskelly_images/2766916.jpg
4619393 COURREGES 58864 /content/udrive/MyDrive/GP5/oskelly_images/4619393.jpg
4639614 THOM BROWNE 139032 /content/udrive/MyDrive/GP5/oskelly_images/4639614.jpg
2573024 DOLCE&GABBANA 176507 /content/udrive/MyDrive/GP5/oskelly_images/2573024.jpg
4798192 DOLCE&GABBANA 85045 /content/udrive/MyDrive/GP5/oskelly_images/4798192.jpg
4086357 MOTHER 34309 /content/udrive/MyDrive/GP5/oskelly_images/4086357.jpg
5304287 BARBOUR 18138 /content/udrive/MyDrive/GP5/oskelly_images/5304287.jpg
5190830 DOLCE&GABBANA 85045 /content/udrive/MyDrive/GP5/oskelly_images/5190830.jpg
5555186 VIVIENNE WESTWOOD 35336 /content/udrive/MyDrive/GP5/oskelly_images/5555186.jpg
4020079 THOM BROWNE 120894 /content/udrive/MyDrive/GP5/oskelly_images/4020079.jpg
3989008 AGOLDE 40555 /content/udrive/MyDrive/GP5/oskelly_images/3989008.jpg
5235390 SACAI 41752 /content/udrive/MyDrive/GP5/oskelly_images/5235390.jpg
2572652 FENDI 246065 /content/udrive/MyDrive/GP5/oskelly_images/2572652.jpg
5223825 LOEWE 598907 /content/udrive/MyDrive/GP5/oskelly_images/5223825.jpg
5259462 RICK OWENS 43378 /content/udrive/MyDrive/GP5/oskelly_images/5259462.jpg
2927392 BRUNELLO CUCINELLI 105921 /content/udrive/MyDrive/GP5/oskelly_images/2927392.jpg
5008600 BURBERRY 34822 /content/udrive/MyDrive/GP5/oskelly_images/5008600.jpg
3802659 R13 92061 /content/udrive/MyDrive/GP5/oskelly_images/3802659.jpg
5061496 BURBERRY 37988 /content/udrive/MyDrive/GP5/oskelly_images/5061496.jpg
5278211 Ami Paris 20363 /content/udrive/MyDrive/GP5/oskelly_images/5278211.jpg
5024141 VIVIENNE WESTWOOD 42266 /content/udrive/MyDrive/GP5/oskelly_images/5024141.jpg
3862835 GANNI 42266 /content/udrive/MyDrive/GP5/oskelly_images/3862835.jpg
5219366 SACAI 88809 /content/udrive/MyDrive/GP5/oskelly_images/5219366.jpg
4697363 GOLDEN GOOSE 117728 /content/udrive/MyDrive/GP5/oskelly_images/4697363.jpg
5287486 SACAI 49795 /content/udrive/MyDrive/GP5/oskelly_images/5287486.jpg
5235812 SACAI 49795 /content/udrive/MyDrive/GP5/oskelly_images/5235812.jpg
3814292 JACQUEMUS 34309 /content/udrive/MyDrive/GP5/oskelly_images/3814292.jpg
4798182 DOLCE&GABBANA 155117 /content/udrive/MyDrive/GP5/oskelly_images/4798182.jpg
3107552 GOLDEN GOOSE 35336 /content/udrive/MyDrive/GP5/oskelly_images/3107552.jpg
4798181 DOLCE&GABBANA 85045 /content/udrive/MyDrive/GP5/oskelly_images/4798181.jpg
4892544 RICK OWENS 50822 /content/udrive/MyDrive/GP5/oskelly_images/4892544.jpg
3655858 MAGDA BUTRYM 88296 /content/udrive/MyDrive/GP5/oskelly_images/3655858.jpg
5186434 DOLCE&GABBANA 187201 /content/udrive/MyDrive/GP5/oskelly_images/5186434.jpg
5113103 MONCLER 24641 /content/udrive/MyDrive/GP5/oskelly_images/5113103.jpg
4898085 RICK OWENS 98991 /content/udrive/MyDrive/GP5/oskelly_images/4898085.jpg
5235362 SACAI 65281 /content/udrive/MyDrive/GP5/oskelly_images/5235362.jpg
2849681 VIVIENNE WESTWOOD 42266 /content/udrive/MyDrive/GP5/oskelly_images/2849681.jpg
3774015 GOLDEN GOOSE 106434 /content/udrive/MyDrive/GP5/oskelly_images/3774015.jpg
2909264 BRUNELLO CUCINELLI 104894 /content/udrive/MyDrive/GP5/oskelly_images/2909264.jpg
3146274 MAISON MARGIELA 73837 /content/udrive/MyDrive/GP5/oskelly_images/3146274.jpg
5438155 POLO RALPH LAUREN 23015 /content/udrive/MyDrive/GP5/oskelly_images/5438155.jpg
2818356 VIVIENNE WESTWOOD 38501 /content/udrive/MyDrive/GP5/oskelly_images/2818356.jpg
5259415 RICK OWENS 85644 /content/udrive/MyDrive/GP5/oskelly_images/5259415.jpg
4717420 MARINE SERRE 36448 /content/udrive/MyDrive/GP5/oskelly_images/4717420.jpg
5235810 SACAI 67420 /content/udrive/MyDrive/GP5/oskelly_images/5235810.jpg
5235361 SACAI 88809 /content/udrive/MyDrive/GP5/oskelly_images/5235361.jpg
2882212 MM6 MAISON MARGIELA 105921 /content/udrive/MyDrive/GP5/oskelly_images/2882212.jpg
5240891 SACAI 28405 /content/udrive/MyDrive/GP5/oskelly_images/5240891.jpg
4917849 RICK OWENS 26780 /content/udrive/MyDrive/GP5/oskelly_images/4917849.jpg
4892521 RICK OWENS 30031 /content/udrive/MyDrive/GP5/oskelly_images/4892521.jpg
4798150 DOLCE&GABBANA 155117 /content/udrive/MyDrive/GP5/oskelly_images/4798150.jpg
5240856 AURALEE 40127 /content/udrive/MyDrive/GP5/oskelly_images/5240856.jpg
4798126 PACO RABANNE 37474 /content/udrive/MyDrive/GP5/oskelly_images/4798126.jpg
2569627 MAISON MARGIELA 73837 /content/udrive/MyDrive/GP5/oskelly_images/2569627.jpg
2969046 DOLCE&GABBANA 48169 /content/udrive/MyDrive/GP5/oskelly_images/2969046.jpg
5228776 SACAI 159395 /content/udrive/MyDrive/GP5/oskelly_images/5228776.jpg
5235421 RICK OWENS 187715 /content/udrive/MyDrive/GP5/oskelly_images/5235421.jpg
5438107 POLO RALPH LAUREN 42266 /content/udrive/MyDrive/GP5/oskelly_images/5438107.jpg
5228780 GOLDEN GOOSE 41752 /content/udrive/MyDrive/GP5/oskelly_images/5228780.jpg
4013172 VICTORIA BECKHAM 41752 /content/udrive/MyDrive/GP5/oskelly_images/4013172.jpg
2568902 OFF-WHITE 26780 /content/udrive/MyDrive/GP5/oskelly_images/2568902.jpg
2568902 OFF-WHITE 26780 /content/udrive/MyDrive/GP5/oskelly_images/2568902.jpg
4617790 COURREGES 105921 /content/udrive/MyDrive/GP5/oskelly_images/4617790.jpg
2942988 R13 62629 /content/udrive/MyDrive/GP5/oskelly_images/2942988.jpg
5235376 SACAI 106434 /content/udrive/MyDrive/GP5/oskelly_images/5235376.jpg
4569860 LEMAIRE 63142 /content/udrive/MyDrive/GP5/oskelly_images/4569860.jpg
3768230 R13 93087 /content/udrive/MyDrive/GP5/oskelly_images/3768230.jpg
3218510 COPERNI 37474 /content/udrive/MyDrive/GP5/oskelly_images/3218510.jpg
2614995 ISABEL MARANT ETOILE 34309 /content/udrive/MyDrive/GP5/oskelly_images/2614995.jpg

In [ ]:
data = pd.DataFrame(all_items)
data.to_excel('all_items_100-200_with_images.xlsx', index=False)
data.head()

,Oskelly ID,url,Размер,Раздел,Категория,Бренд,Материал одежды,Цвет,Состояние товара,Продавец,...,Скидка,Описание,Название,Состояние,image_url,image_path,Модель,Посадка,Материал джинсов,Винтаж
0,4042481,https://oskelly.ru/products/vechernee-plate-ch...,IT 42,Женское,Вечерние платья,CHRISTIAN DIOR,Другое,Темно-синий,Отличное состояние,Частный продавец,...,-56%,"🏛️ Лот: Christian Dior ""Midnight Blue"" Guipure...",CHRISTIAN DIORТемно-синее вечернее платьеТемно...,Отличное состояние,https://static.cdn.oskelly.ru/product/4042481/...,/content/udrive/MyDrive/GP5/oskelly_images/404...,NaN,NaN,NaN,NaN
1,2808593,https://oskelly.ru/products/vechernee-plate-ra...,US 4,Женское,Вечерние платья,RALPH LAUREN,Другое,Другое,Отличное состояние,Частный продавец,...,-88%,💎 MUSEUM PIECE: \n1 OF 2 IN THE WORLD | \nRALP...,RALPH LAURENВечернее платьеВечернее платье,Отличное состояние,https://static.cdn.oskelly.ru/product/2808593/...,/content/udrive/MyDrive/GP5/oskelly_images/280...,NaN,NaN,NaN,NaN
2,3687937,https://oskelly.ru/products/vechernee-plate-lo...,FR 36,Женское,Вечерние платья,LOUIS VUITTON,Шелк,Белый,Отличное состояние,Частный продавец,...,-62%,"Потрясающее, восхитительное, идеальное, прекра...",LOUIS VUITTONБелое шелковое вечернее платьеБел...,Отличное состояние,https://static.cdn.oskelly.ru/product/3687937/...,/content/udrive/MyDrive/GP5/oskelly_images/368...,NaN,NaN,NaN,NaN
3,2282562,https://oskelly.ru/products/shuba-gucci-pre-ow...,EU 40,Женское,Шубы,GUCCI,Другое,Мульти,Отличное состояние,Частный продавец,...,-91%,Gucci Runway Archive — «THE FINAL FUR» | Aless...,"GUCCI, Мульти шуба • GGGGМульти шуба",Отличное состояние,https://static.cdn.oskelly.ru/product/2282562/...,/content/udrive/MyDrive/GP5/oskelly_images/228...,GG,NaN,NaN,NaN
4,2783927,https://oskelly.ru/products/zhaketpidzhak-gucc...,IT 40,Женское,Жакеты и пиджаки,GUCCI,Шелк,Мульти,Отличное состояние,Частный продавец,...,-64%,🎹 GUCCI x ELTON JOHN: Heritage Piece & Museum ...,GUCCIМульти шелковый жакет/пиджакМульти шелков...,Отличное состояние,https://static.cdn.oskelly.ru/product/2783927/...,/content/udrive/MyDrive/GP5/oskelly_images/278...,NaN,NaN,NaN,NaN

In [ ]:
all_items = []

for i in range(200, 700):
  url = 'https://oskelly.ru' + items.iloc[i, 0]
  oskelly = requests.get(url, headers=headers)

  if oskelly.status_code == 200:
    soup = BeautifulSoup(oskelly.text, 'html')
    item = {}

    item_id = items.iloc[i, 0].split('-')[-1]
    item['Oskelly ID'] = item_id
    item['url'] = url

    for elem in soup.find_all('li', class_='osk-product-attributes__item'):
      name_elem = elem.find('span', class_='osk-product-attributes__item-name')
      value_elem = elem.find('span', class_='osk-product-attributes__item-value')

      if name_elem and value_elem:
        category = name_elem.text.strip()
        value = value_elem.text.strip()
        item[category] = value

    price = soup.find('span', class_='osk-product__rrpPrice')
    if price:
      item['Цена'] = price.text.replace('\xa0', '').replace('₽', '').strip()

    discount = soup.find('span', class_='osk-product__discount')
    if discount:
      item['Скидка'] = discount.text.strip()

    price2 = soup.find('span', class_='osk-product__price')
    if price2 and 'Цена' not in item:
      item['Цена'] = price2.text.replace('\xa0', '').replace('₽', '').strip()


    description = soup.find('div', class_='osk-product-seller__description')
    if description:
      item['Описание'] = description.text.strip()


    brand = soup.find('a', class_='osk-product__brand')
    if brand:
      item['Бренд'] = brand.text.strip()


    title = soup.find('h1', class_='osk-product__title')
    if title:
      item['Название'] = title.text.strip()


    condition = soup.find('div', class_='osk-product__condition')
    if condition:
      item['Состояние'] = condition.text.strip()


    image_url = get_main_product_image_url(soup)
    image_path = download_main_product_image(image_url=image_url,item_id=item_id,images_dir=images_dir)

    item['image_url'] = image_url
    item['image_path'] = image_path

    all_items.append(item)

    print(item_id, item.get('Бренд'), item.get('Цена'), image_path)

  time.sleep(0.5)

2567345 KHAITE 30957 /content/udrive/MyDrive/GP5/oskelly_imagess/2567345.jpg
3592720 JIL SANDER 39485 /content/udrive/MyDrive/GP5/oskelly_imagess/3592720.jpg
5468926 MAISON KITSUNE 30957 /content/udrive/MyDrive/GP5/oskelly_imagess/5468926.jpg
5287345 RICK OWENS 69332 /content/udrive/MyDrive/GP5/oskelly_imagess/5287345.jpg
5221187 SACAI 74108 /content/udrive/MyDrive/GP5/oskelly_imagess/5221187.jpg
4011377 AGOLDE 40423 /content/udrive/MyDrive/GP5/oskelly_imagess/4011377.jpg
3054088 FENDI 154612 /content/udrive/MyDrive/GP5/oskelly_imagess/3054088.jpg
3075880 ISABEL MARANT 26693 /content/udrive/MyDrive/GP5/oskelly_imagess/3075880.jpg
5073983 THE ATTICO 26693 /content/udrive/MyDrive/GP5/oskelly_imagess/5073983.jpg
3019488 DOLCE&GABBANA 31468 /content/udrive/MyDrive/GP5/oskelly_imagess/3019488.jpg
3120451 DOLCE&GABBANA 42128 /content/udrive/MyDrive/GP5/oskelly_imagess/3120451.jpg
5259395 RICK OWENS 229232 /content/udrive/MyDrive/GP5/oskelly_imagess/5259395.jpg
5223751 None None /content/udrive/MyDrive/GP5/oskelly_imagess/5223751.jpg
5219774 SACAI 74108 /content/udrive/MyDrive/GP5/oskelly_imagess/5219774.jpg
5287340 RICK OWENS 190345 /content/udrive/MyDrive/GP5/oskelly_imagess/5287340.jpg
5235336 RICK OWENS 50656 /content/udrive/MyDrive/GP5/oskelly_imagess/5235336.jpg
2612318 FENDI 104553 /content/udrive/MyDrive/GP5/oskelly_imagess/2612318.jpg
2565046 DOLCE&GABBANA 63448 /content/udrive/MyDrive/GP5/oskelly_imagess/2565046.jpg
5240844 AURALEE 39996 /content/udrive/MyDrive/GP5/oskelly_imagess/5240844.jpg
5168368 POLO RALPH LAUREN 18676 /content/udrive/MyDrive/GP5/oskelly_imagess/5168368.jpg
5194498 DOLCE&GABBANA 122632 /content/udrive/MyDrive/GP5/oskelly_imagess/5194498.jpg
4732805 BRUNELLO CUCINELLI 91761 /content/udrive/MyDrive/GP5/oskelly_imagess/4732805.jpg
4798011 DOLCE&GABBANA 293192 /content/udrive/MyDrive/GP5/oskelly_imagess/4798011.jpg
5287315 SACAI 84768 /content/udrive/MyDrive/GP5/oskelly_imagess/5287315.jpg
4798017 DOLCE&GABBANA 58673 /content/udrive/MyDrive/GP5/oskelly_imagess/4798017.jpg
5468818 GOLDEN GOOSE 116236 /content/udrive/MyDrive/GP5/oskelly_imagess/5468818.jpeg
5438135 POLO RALPH LAUREN 22940 /content/udrive/MyDrive/GP5/oskelly_imagess/5438135.jpg
4009581 POLO RALPH LAUREN 22940 /content/udrive/MyDrive/GP5/oskelly_imagess/4009581.jpg
5287382 RICK OWENS 95428 /content/udrive/MyDrive/GP5/oskelly_imagess/5287382.jpg
3059605 COPERNI 26693 /content/udrive/MyDrive/GP5/oskelly_imagess/3059605.jpg
5237149 ISABEL MARANT ETOILE 69559 /content/udrive/MyDrive/GP5/oskelly_imagess/5237149.jpg
5143938 ROTATE 41752 /content/udrive/MyDrive/GP5/oskelly_imagess/5143938.jpg
3361492 SAINT LAURENT 75000 /content/udrive/MyDrive/GP5/oskelly_imagess/3361492.jpg
5348722 ALO YOGA 13500 /content/udrive/MyDrive/GP5/oskelly_imagess/5348722.jpg
4580438 CHANEL 90000 /content/udrive/MyDrive/GP5/oskelly_imagess/4580438.jpg
1128728 PINKO 39990 /content/udrive/MyDrive/GP5/oskelly_imagess/1128728.jpg
5225442 VALENTINO 100000 /content/udrive/MyDrive/GP5/oskelly_imagess/5225442.jpeg
2156738 CALVIN KLEIN 13000 /content/udrive/MyDrive/GP5/oskelly_imagess/2156738.jpg
5897652 BALENCIAGA 62936 /content/udrive/MyDrive/GP5/oskelly_imagess/5897652.jpg
5897663 BALENCIAGA 48013 /content/udrive/MyDrive/GP5/oskelly_imagess/5897663.jpg
5921555 WOLFORD 19785 /content/udrive/MyDrive/GP5/oskelly_imagess/5921555.jpg
5897619 COURREGES 62936 /content/udrive/MyDrive/GP5/oskelly_imagess/5897619.jpg
5921556 WOLFORD 16544 /content/udrive/MyDrive/GP5/oskelly_imagess/5921556.jpg
5921558 WOLFORD 39996 /content/udrive/MyDrive/GP5/oskelly_imagess/5921558.jpg
5572296 WOLFORD 19785 /content/udrive/MyDrive/GP5/oskelly_imagess/5572296.jpg
5921559 WOLFORD 20808 /content/udrive/MyDrive/GP5/oskelly_imagess/5921559.jpg
5921568 WOLFORD 21917 /content/udrive/MyDrive/GP5/oskelly_imagess/5921568.jpg
5866838 ALEXANDER WANG 19785 /content/udrive/MyDrive/GP5/oskelly_imagess/5866838.jpg
5363007 BLUGIRL 17000 /content/udrive/MyDrive/GP5/oskelly_imagess/5363007.jpg
852443 VICTORIA BECKHAM 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/852443.jpg
3158819 VERSACE 19000 /content/udrive/MyDrive/GP5/oskelly_imagess/3158819.jpg
1905081 VICTORIA BECKHAM 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/1905081.jpg
4542581 VERSACE COLLECTION 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/4542581.jpg
4849402 JUICY COUTURE 33000 /content/udrive/MyDrive/GP5/oskelly_imagess/4849402.jpg
741606 VICTORIA BECKHAM 32000 /content/udrive/MyDrive/GP5/oskelly_imagess/741606.jpg
5915188 MAX MARA 43663 /content/udrive/MyDrive/GP5/oskelly_imagess/5915188.jpg
3227057 VICTORIA BECKHAM 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/3227057.jpg
723021 VICTORIA BECKHAM 28000 /content/udrive/MyDrive/GP5/oskelly_imagess/723021.jpg
4710971 BLUMARINE 26000 /content/udrive/MyDrive/GP5/oskelly_imagess/4710971.jpg
5916375 'S MAX MARA 32020 /content/udrive/MyDrive/GP5/oskelly_imagess/5916375.jpg
3233312 VICTORIA BECKHAM 55000 /content/udrive/MyDrive/GP5/oskelly_imagess/3233312.jpg
4945810 YVES SALOMON 150000 /content/udrive/MyDrive/GP5/oskelly_imagess/4945810.jpg
5916385 'S MAX MARA 34910 /content/udrive/MyDrive/GP5/oskelly_imagess/5916385.jpg
4345181 404NOTFOUND 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/4345181.jpg
5916393 'S MAX MARA 34910 /content/udrive/MyDrive/GP5/oskelly_imagess/5916393.jpg
5907148 WOLFORD 36000 /content/udrive/MyDrive/GP5/oskelly_imagess/5907148.jpg
2092285 DOLCE&GABBANA 90000 /content/udrive/MyDrive/GP5/oskelly_imagess/2092285.jpg
5886840 TOM FORD 148216 /content/udrive/MyDrive/GP5/oskelly_imagess/5886840.jpg
5915120 MAX MARA 62936 /content/udrive/MyDrive/GP5/oskelly_imagess/5915120.jpg
5922899 LOEWE 51168 /content/udrive/MyDrive/GP5/oskelly_imagess/5922899.jpg
5398877 Harley Davidson 150000 /content/udrive/MyDrive/GP5/oskelly_imagess/5398877.jpg
5276481 RED VALENTINO 24000 /content/udrive/MyDrive/GP5/oskelly_imagess/5276481.jpg
5915286 MAX MARA 62936 /content/udrive/MyDrive/GP5/oskelly_imagess/5915286.jpg
5533426 CHANEL 950000 /content/udrive/MyDrive/GP5/oskelly_imagess/5533426.jpg
5613598 TWIN-SET 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/5613598.jpeg
5335266 BRUNELLO CUCINELLI 120000 /content/udrive/MyDrive/GP5/oskelly_imagess/5335266.jpg
5385425 CELINE 12000 /content/udrive/MyDrive/GP5/oskelly_imagess/5385425.jpg
5291402 COMME DES GARÇONS 12000 /content/udrive/MyDrive/GP5/oskelly_imagess/5291402.jpg
459682 BALMAIN 550000 /content/udrive/MyDrive/GP5/oskelly_imagess/459682.jpg
5292630 JACOB COHEN 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5292630.jpg
5385436 EMILIO PUCCI 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5385436.jpg
5331112 ISABEL MARANT ETOILE 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5331112.jpg
5292818 SAINT LAURENT 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/5292818.jpg
898549 CHANEL 395000 /content/udrive/MyDrive/GP5/oskelly_imagess/898549.jpg
5291419 EMILIO PUCCI 13000 /content/udrive/MyDrive/GP5/oskelly_imagess/5291419.jpg
5887950 ZIMMERMANN 71976 /content/udrive/MyDrive/GP5/oskelly_imagess/5887950.jpg
5445832 BALENCIAGA 28000 /content/udrive/MyDrive/GP5/oskelly_imagess/5445832.jpg
5867530 DARKPARK 66200 /content/udrive/MyDrive/GP5/oskelly_imagess/5867530.jpg
4154034 CHRISTIAN DIOR 88000 /content/udrive/MyDrive/GP5/oskelly_imagess/4154034.jpg
2695565 SANDRO 34000 /content/udrive/MyDrive/GP5/oskelly_imagess/2695565.jpg
5913667 FENDI 245179 /content/udrive/MyDrive/GP5/oskelly_imagess/5913667.jpg
3449431 SANDRO 28000 /content/udrive/MyDrive/GP5/oskelly_imagess/3449431.jpg
5913661 BRUNELLO CUCINELLI 1012698 /content/udrive/MyDrive/GP5/oskelly_imagess/5913661.jpg
3488740 PINKO 21000 /content/udrive/MyDrive/GP5/oskelly_imagess/3488740.jpg
4193436 SAINT LAURENT 215000 /content/udrive/MyDrive/GP5/oskelly_imagess/4193436.jpg
5915951 THE FRANKIE SHOP 23537 /content/udrive/MyDrive/GP5/oskelly_imagess/5915951.jpeg
5922329 MIU MIU 31000 /content/udrive/MyDrive/GP5/oskelly_imagess/5922329.jpg
644589 ETRO 27000 /content/udrive/MyDrive/GP5/oskelly_imagess/644589.jpg
4243326 Eres 12000 /content/udrive/MyDrive/GP5/oskelly_imagess/4243326.jpg
5329955 BALMAIN 13000 /content/udrive/MyDrive/GP5/oskelly_imagess/5329955.jpg
621043 ARMANI JEANS 13000 /content/udrive/MyDrive/GP5/oskelly_imagess/621043.jpg
3566513 MCQ ALEXANDER MCQUEEN 69950 /content/udrive/MyDrive/GP5/oskelly_imagess/3566513.jpg
1461943 DOLCE&GABBANA 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/1461943.jpg
1455396 SPORTMAX 55000 /content/udrive/MyDrive/GP5/oskelly_imagess/1455396.jpg
498779 THEORY 27000 /content/udrive/MyDrive/GP5/oskelly_imagess/498779.jpg
2554709 CHLOE 70000 /content/udrive/MyDrive/GP5/oskelly_imagess/2554709.jpg
3759265 ZIMMERMANN 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/3759265.jpg
2358899 ISABEL MARANT ETOILE 42000 /content/udrive/MyDrive/GP5/oskelly_imagess/2358899.jpg
5516722 BALENCIAGA 54000 /content/udrive/MyDrive/GP5/oskelly_imagess/5516722.jpg
5850462 GUCCI 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/5850462.jpg
1877496 ZIMMERMANN 45000 /content/udrive/MyDrive/GP5/oskelly_imagess/1877496.jpg
1053978 NANUSHKA 67000 /content/udrive/MyDrive/GP5/oskelly_imagess/1053978.jpg
5850441 VETEMENTS 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/5850441.jpg
1131099 ISABEL MARANT 50000 /content/udrive/MyDrive/GP5/oskelly_imagess/1131099.jpg
1718923 LOULOU STUDIO 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/1718923.jpg
1718995 LOEWE 50000 /content/udrive/MyDrive/GP5/oskelly_imagess/1718995.jpg
1779181 MAX MARA 52000 /content/udrive/MyDrive/GP5/oskelly_imagess/1779181.jpg
5207813 JOSEPH 16000 /content/udrive/MyDrive/GP5/oskelly_imagess/5207813.jpg
5899362 VALENTINO 75000 /content/udrive/MyDrive/GP5/oskelly_imagess/5899362.jpg
5257568 EQUIPMENT 16000 /content/udrive/MyDrive/GP5/oskelly_imagess/5257568.jpg
5567318 DIANE VON FURSTENBERG 24000 /content/udrive/MyDrive/GP5/oskelly_imagess/5567318.jpg
1295210 JIL SANDER 50000 /content/udrive/MyDrive/GP5/oskelly_imagess/1295210.jpg
560255 ISABEL MARANT ETOILE 27000 /content/udrive/MyDrive/GP5/oskelly_imagess/560255.jpg
3951140 FORTE COUTURE 17000 /content/udrive/MyDrive/GP5/oskelly_imagess/3951140.jpg
5725004 120% LINO 45000 /content/udrive/MyDrive/GP5/oskelly_imagess/5725004.jpg
5858959 SKIMS 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5858959.jpeg
5913048 DIESEL 10020 /content/udrive/MyDrive/GP5/oskelly_imagess/5913048.jpg
5691475 MICHAEL KORS 65000 /content/udrive/MyDrive/GP5/oskelly_imagess/5691475.jpg
502663 ISABEL MARANT ETOILE 36000 /content/udrive/MyDrive/GP5/oskelly_imagess/502663.jpg
1210818 VERSACE 39000 /content/udrive/MyDrive/GP5/oskelly_imagess/1210818.jpg
5630873 LANVIN 75000 /content/udrive/MyDrive/GP5/oskelly_imagess/5630873.jpg
5915202 FENDI 55432 /content/udrive/MyDrive/GP5/oskelly_imagess/5915202.jpg
4406820 LOULOU DE SAISON 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/4406820.jpg
2736599 TOTEME 49000 /content/udrive/MyDrive/GP5/oskelly_imagess/2736599.jpg
498768 BURBERRY 80000 /content/udrive/MyDrive/GP5/oskelly_imagess/498768.jpg
3085582 OFF-WHITE 135000 /content/udrive/MyDrive/GP5/oskelly_imagess/3085582.jpg
2247940 ETRO 36000 /content/udrive/MyDrive/GP5/oskelly_imagess/2247940.jpg
5636051 BALENCIAGA 31500 /content/udrive/MyDrive/GP5/oskelly_imagess/5636051.jpg
715142 MAX MARA STUDIO 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/715142.jpg
5566927 WEEKEND MAX MARA 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/5566927.jpg
5636098 CHRISTOPHER ESBER 31500 /content/udrive/MyDrive/GP5/oskelly_imagess/5636098.jpg
5517107 LOUIS VUITTON 90000 /content/udrive/MyDrive/GP5/oskelly_imagess/5517107.jpg
3159843 VERSACE 23400 /content/udrive/MyDrive/GP5/oskelly_imagess/3159843.jpg
4047772 BLUMARINE 23400 /content/udrive/MyDrive/GP5/oskelly_imagess/4047772.jpg
5424430 SELF-PORTRAIT 23400 /content/udrive/MyDrive/GP5/oskelly_imagess/5424430.jpg
5922541 ALAIA 49000 /content/udrive/MyDrive/GP5/oskelly_imagess/5922541.jpeg
5922515 DIESEL 15000 /content/udrive/MyDrive/GP5/oskelly_imagess/5922515.jpeg
508244 MAJE 28000 /content/udrive/MyDrive/GP5/oskelly_imagess/508244.jpg
5920111 ZIMMERMANN 80000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920111.jpg
1387586 CHANEL 860000 /content/udrive/MyDrive/GP5/oskelly_imagess/1387586.jpg
5643418 HERON PRESTON 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5643418.jpg
5912893 PRADA 149240 /content/udrive/MyDrive/GP5/oskelly_imagess/5912893.jpeg
5707815 OSEREE 29848 /content/udrive/MyDrive/GP5/oskelly_imagess/5707815.jpg
5910648 FENDI 91420 /content/udrive/MyDrive/GP5/oskelly_imagess/5910648.jpeg
5707619 OSEREE 29848 /content/udrive/MyDrive/GP5/oskelly_imagess/5707619.jpg
5323470 OSEREE 21320 /content/udrive/MyDrive/GP5/oskelly_imagess/5323470.jpg
5616196 OSEREE 27716 /content/udrive/MyDrive/GP5/oskelly_imagess/5616196.jpg
5707752 OSEREE 27716 /content/udrive/MyDrive/GP5/oskelly_imagess/5707752.jpg
5707753 OSEREE 27716 /content/udrive/MyDrive/GP5/oskelly_imagess/5707753.jpg
5921183 ALAIA 155000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921183.jpg
5864890 BALENCIAGA 36000 /content/udrive/MyDrive/GP5/oskelly_imagess/5864890.jpg
5921180 ALAIA 175000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921180.webp
5921186 ALAIA 210000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921186.jpg
5899273 BALMAIN 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/5899273.jpg
5779003 MOSCHINO 26181 /content/udrive/MyDrive/GP5/oskelly_imagess/5779003.jpg
5778887 MM6 MAISON MARGIELA 39485 /content/udrive/MyDrive/GP5/oskelly_imagess/5778887.jpg
5778472 MOSCHINO 22429 /content/udrive/MyDrive/GP5/oskelly_imagess/5778472.jpg
5778530 PS BY PAUL SMITH 11540 /content/udrive/MyDrive/GP5/oskelly_imagess/5778530.jpg
5778538 MOSCHINO 26181 /content/udrive/MyDrive/GP5/oskelly_imagess/5778538.jpg
5778668 COMME DES GARÇONS PLAY 12340 /content/udrive/MyDrive/GP5/oskelly_imagess/5778668.jpg
5778587 MOSCHINO 22429 /content/udrive/MyDrive/GP5/oskelly_imagess/5778587.jpg
5778596 MOSCHINO 22429 /content/udrive/MyDrive/GP5/oskelly_imagess/5778596.jpg
5778480 MOSCHINO 26960 /content/udrive/MyDrive/GP5/oskelly_imagess/5778480.jpg
5922096 DOLCE&GABBANA 98000 /content/udrive/MyDrive/GP5/oskelly_imagess/5922096.jpg
5922126 DOLCE&GABBANA 98000 /content/udrive/MyDrive/GP5/oskelly_imagess/5922126.jpg
5922147 GUCCI 73500 /content/udrive/MyDrive/GP5/oskelly_imagess/5922147.jpg
5777367 MOSCHINO 22429 /content/udrive/MyDrive/GP5/oskelly_imagess/5777367.jpg
5921711 MIU MIU 90000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921711.jpg
5777596 ROTATE 22940 /content/udrive/MyDrive/GP5/oskelly_imagess/5777596.jpg
2061450 CHLOE 90000 /content/udrive/MyDrive/GP5/oskelly_imagess/2061450.jpg
5777213 MOSCHINO 20808 /content/udrive/MyDrive/GP5/oskelly_imagess/5777213.jpg
5921844 ALEXANDER MCQUEEN 150000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921844.jpg
652112 GIORGIO ARMANI 120000 /content/udrive/MyDrive/GP5/oskelly_imagess/652112.jpg
5922218 ALEXANDER WANG 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/5922218.jpg
5831276 JACQUEMUS 19000 /content/udrive/MyDrive/GP5/oskelly_imagess/5831276.jpg
5922114 GUCCI 47000 /content/udrive/MyDrive/GP5/oskelly_imagess/5922114.jpg
5663655 CELINE 70000 /content/udrive/MyDrive/GP5/oskelly_imagess/5663655.jpg
5922480 ROBERTO CAVALLI 17000 /content/udrive/MyDrive/GP5/oskelly_imagess/5922480.jpg
5922414 CHANEL 39000 /content/udrive/MyDrive/GP5/oskelly_imagess/5922414.jpg
2229720 DRIES VAN NOTEN 85000 /content/udrive/MyDrive/GP5/oskelly_imagess/2229720.jpg
5776001 COPERNI 16033 /content/udrive/MyDrive/GP5/oskelly_imagess/5776001.jpg
5892517 TOM FORD 90000 /content/udrive/MyDrive/GP5/oskelly_imagess/5892517.jpg
5884585 PRADA 80000 /content/udrive/MyDrive/GP5/oskelly_imagess/5884585.jpg
5912748 LORO PIANA 140000 /content/udrive/MyDrive/GP5/oskelly_imagess/5912748.jpeg
5912617 LORO PIANA 125000 /content/udrive/MyDrive/GP5/oskelly_imagess/5912617.jpeg
5296921 ARMANI COLLEZIONI 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5296921.jpg
5775015 GIVENCHY 52277 /content/udrive/MyDrive/GP5/oskelly_imagess/5775015.jpg
5774727 GIVENCHY 52277 /content/udrive/MyDrive/GP5/oskelly_imagess/5774727.jpg
5774289 MOSCHINO 27204 /content/udrive/MyDrive/GP5/oskelly_imagess/5774289.jpg
3670054 VERSACE 90000 /content/udrive/MyDrive/GP5/oskelly_imagess/3670054.jpg
5774664 MOSCHINO 26181 /content/udrive/MyDrive/GP5/oskelly_imagess/5774664.jpg
5773620 COPERNI 16033 /content/udrive/MyDrive/GP5/oskelly_imagess/5773620.jpg
5773685 VETEMENTS 62936 /content/udrive/MyDrive/GP5/oskelly_imagess/5773685.jpg
5916962 VERSACE 298479 /content/udrive/MyDrive/GP5/oskelly_imagess/5916962.jpg
5773129 STELLA MCCARTNEY 52277 /content/udrive/MyDrive/GP5/oskelly_imagess/5773129.jpg
5773327 CARHARTT 11769 /content/udrive/MyDrive/GP5/oskelly_imagess/5773327.jpg
2328809 COS 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/2328809.jpg
5773486 CARHARTT 11769 /content/udrive/MyDrive/GP5/oskelly_imagess/5773486.jpg
1982234 PRADA 80000 /content/udrive/MyDrive/GP5/oskelly_imagess/1982234.jpg
3317746 LOUIS VUITTON 110000 /content/udrive/MyDrive/GP5/oskelly_imagess/3317746.jpg
5893404 COURREGES 105576 /content/udrive/MyDrive/GP5/oskelly_imagess/5893404.jpg
5893455 COURREGES 105576 /content/udrive/MyDrive/GP5/oskelly_imagess/5893455.jpg
5916961 VERSACE 159900 /content/udrive/MyDrive/GP5/oskelly_imagess/5916961.jpg
5101113 POLO RALPH LAUREN 13460 /content/udrive/MyDrive/GP5/oskelly_imagess/5101113.jpg
5922770 CHANEL 1542000 /content/udrive/MyDrive/GP5/oskelly_imagess/5922770.jpg
5511283 SONIA RYKIEL 23500 /content/udrive/MyDrive/GP5/oskelly_imagess/5511283.jpg
1303503 SAINT LAURENT 63000 /content/udrive/MyDrive/GP5/oskelly_imagess/1303503.jpeg
5907987 Ami Paris 25584 /content/udrive/MyDrive/GP5/oskelly_imagess/5907987.jpg
5907980 GIVENCHY 138580 /content/udrive/MyDrive/GP5/oskelly_imagess/5907980.jpg
5916989 JIL SANDER 37710 /content/udrive/MyDrive/GP5/oskelly_imagess/5916989.jpg
5916992 JIL SANDER 48890 /content/udrive/MyDrive/GP5/oskelly_imagess/5916992.jpg
5916996 JIL SANDER 48890 /content/udrive/MyDrive/GP5/oskelly_imagess/5916996.jpg
5916993 JIL SANDER 282532 /content/udrive/MyDrive/GP5/oskelly_imagess/5916993.jpg
5922217 BLUGIRL 35500 /content/udrive/MyDrive/GP5/oskelly_imagess/5922217.jpg
5922357 ZIMMERMANN 165000 /content/udrive/MyDrive/GP5/oskelly_imagess/5922357.jpg
5541867 ARMA 95855 /content/udrive/MyDrive/GP5/oskelly_imagess/5541867.jpg
2831377 BALMAIN 275000 /content/udrive/MyDrive/GP5/oskelly_imagess/2831377.jpg
5921484 SEMICOUTURE 27400 /content/udrive/MyDrive/GP5/oskelly_imagess/5921484.jpg
5922168 BALENCIAGA 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/5922168.jpg
5922208 MOSCHINO 11000 /content/udrive/MyDrive/GP5/oskelly_imagess/5922208.jpg
5831279 ACNE STUDIOS 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/5831279.jpg
5922004 SEMICOUTURE 26700 /content/udrive/MyDrive/GP5/oskelly_imagess/5922004.jpg
5922242 ALAIA 23000 /content/udrive/MyDrive/GP5/oskelly_imagess/5922242.jpg
5922256 BURBERRY 148500 /content/udrive/MyDrive/GP5/oskelly_imagess/5922256.jpg
5921522 PATRIZIA PEPE 26500 /content/udrive/MyDrive/GP5/oskelly_imagess/5921522.jpg
5921696 SEMICOUTURE 33000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921696.jpg
5886664 MIU MIU 364200 /content/udrive/MyDrive/GP5/oskelly_imagess/5886664.jpg
5831275 LORO PIANA 13000 /content/udrive/MyDrive/GP5/oskelly_imagess/5831275.jpg
5831136 TOTEME 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5831136.jpg
5922195 PHILOSOPHY DI LORENZO SERAFINI 28500 /content/udrive/MyDrive/GP5/oskelly_imagess/5922195.jpg
5916959 VERSACE 70190 /content/udrive/MyDrive/GP5/oskelly_imagess/5916959.jpg
2788757 VETEMENTS 99000 /content/udrive/MyDrive/GP5/oskelly_imagess/2788757.jpg
5916999 JIL SANDER 94916 /content/udrive/MyDrive/GP5/oskelly_imagess/5916999.jpeg
5539930 Ami Paris 34197 /content/udrive/MyDrive/GP5/oskelly_imagess/5539930.jpg
5916997 JIL SANDER 148216 /content/udrive/MyDrive/GP5/oskelly_imagess/5916997.jpg
5922684 VIVIENNE WESTWOOD 74108 /content/udrive/MyDrive/GP5/oskelly_imagess/5922684.jpg

In [ ]:
data = pd.DataFrame(all_items)
data.to_excel('all_items_200-700_with_images.xlsx', index=False)
data.head()

,Oskelly ID,url,Размер,Раздел,Категория,Бренд,Материал одежды,Цвет,Состояние товара,Продавец,...,Скидка,Описание,Название,Состояние,image_url,image_path,Посадка,Материал джинсов,Модель,Винтаж
0,2567345,https://oskelly.ru/products/futbolka-khaite-ne...,INT M/L/XL,Женское,Футболки,KHAITE,Хлопок,Белый,Новое с биркой,Бутик,...,-32%,Cotton crew neck t-shirt with logo label on th...,KHAITEБелая хлопковая футболкаБелая хлопковая ...,Новое с биркой,https://static.cdn.oskelly.ru/product/2567345/...,/content/udrive/MyDrive/GP5/oskelly_imagess/25...,NaN,NaN,NaN,NaN
1,3592720,https://oskelly.ru/products/futbolka-jil-sande...,INT XS/S,Женское,Футболки,JIL SANDER,Хлопок,Мульти,Новое с биркой,Бутик,...,-32%,"Striped, heavy cotton jersey crew neck t-shirt...",JIL SANDERМульти хлопковая футболкаМульти хлоп...,Новое с биркой,https://static.cdn.oskelly.ru/product/3592720/...,/content/udrive/MyDrive/GP5/oskelly_imagess/35...,NaN,NaN,NaN,NaN
2,5468926,https://oskelly.ru/products/kardigan-maison-ki...,INT XS,Женское,Кардиганы,MAISON KITSUNE,Шерсть,Бежевый,Новое с биркой,Бутик,...,-32%,"Кардиган из экстрафайн шерсти, с нашивкой Baby...",MAISON KITSUNEБежевый шерстяной кардиганБежевы...,Новое с биркой,https://static.cdn.oskelly.ru/product/5468926/...,/content/udrive/MyDrive/GP5/oskelly_imagess/54...,NaN,NaN,NaN,NaN
3,5287345,https://oskelly.ru/products/pryamye-bryuki-ric...,IT 40,Женское,Прямые брюки,RICK OWENS,Другое,Серый,Новое с биркой,Бутик,...,-40%,"'Bias' silk blend pants, ribbed elastic waistb...",RICK OWENSСерые прямые брюкиСерые прямые брюки,Новое с биркой,https://static.cdn.oskelly.ru/product/5287345/...,/content/udrive/MyDrive/GP5/oskelly_imagess/52...,Средняя,NaN,NaN,NaN
4,5221187,https://oskelly.ru/products/khuditolstovka-sac...,INT L,Женское,Худи и толстовки,SACAI,Хлопок,Серый,Новое с биркой,Бутик,...,-35%,'Sponge' hoodie in mélange cotton blend with n...,SACAIХуди/толстовкаХуди/толстовка,Новое с биркой,https://static.cdn.oskelly.ru/product/5221187/...,/content/udrive/MyDrive/GP5/oskelly_imagess/52...,NaN,NaN,NaN,NaN

In [ ]:
all_items = []

for i in range(700, 1500):
  url = 'https://oskelly.ru' + items.iloc[i, 0]
  oskelly = requests.get(url, headers=headers)

  if oskelly.status_code == 200:
    soup = BeautifulSoup(oskelly.text, 'html')
    item = {}

    item_id = items.iloc[i, 0].split('-')[-1]
    item['Oskelly ID'] = item_id
    item['url'] = url

    for elem in soup.find_all('li', class_='osk-product-attributes__item'):
      name_elem = elem.find('span', class_='osk-product-attributes__item-name')
      value_elem = elem.find('span', class_='osk-product-attributes__item-value')

      if name_elem and value_elem:
        category = name_elem.text.strip()
        value = value_elem.text.strip()
        item[category] = value

    price = soup.find('span', class_='osk-product__rrpPrice')
    if price:
      item['Цена'] = price.text.replace('\xa0', '').replace('₽', '').strip()

    discount = soup.find('span', class_='osk-product__discount')
    if discount:
      item['Скидка'] = discount.text.strip()

    price2 = soup.find('span', class_='osk-product__price')
    if price2 and 'Цена' not in item:
      item['Цена'] = price2.text.replace('\xa0', '').replace('₽', '').strip()


    description = soup.find('div', class_='osk-product-seller__description')
    if description:
      item['Описание'] = description.text.strip()


    brand = soup.find('a', class_='osk-product__brand')
    if brand:
      item['Бренд'] = brand.text.strip()


    title = soup.find('h1', class_='osk-product__title')
    if title:
      item['Название'] = title.text.strip()


    condition = soup.find('div', class_='osk-product__condition')
    if condition:
      item['Состояние'] = condition.text.strip()


    image_url = get_main_product_image_url(soup)
    image_path = download_main_product_image(image_url=image_url,item_id=item_id,images_dir=images_dir)

    item['image_url'] = image_url
    item['image_path'] = image_path

    all_items.append(item)

    print(item_id, item.get('Бренд'), item.get('Цена'), image_path)

  time.sleep(0.5)

3598842 JOHANNA ORTIZ 97000 /content/udrive/MyDrive/GP5/oskelly_imagess/3598842.jpg
2334055 ALEXANDER MCQUEEN 127000 /content/udrive/MyDrive/GP5/oskelly_imagess/2334055.jpg
5921710 POLO RALPH LAUREN 50000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921710.jpeg
2139948 ZIMMERMANN 78000 /content/udrive/MyDrive/GP5/oskelly_imagess/2139948.jpg
5918765 GUCCI 149240 /content/udrive/MyDrive/GP5/oskelly_imagess/5918765.jpg
1898884 THEORY 47000 /content/udrive/MyDrive/GP5/oskelly_imagess/1898884.jpg
1093326 MISSONI 72000 /content/udrive/MyDrive/GP5/oskelly_imagess/1093326.jpg
5922288 MIU MIU 275027 /content/udrive/MyDrive/GP5/oskelly_imagess/5922288.jpg
5865962 COURREGES 84427 /content/udrive/MyDrive/GP5/oskelly_imagess/5865962.jpeg
2031254 DSQUARED2 76000 /content/udrive/MyDrive/GP5/oskelly_imagess/2031254.jpg
2668086 MAX MARA 64000 /content/udrive/MyDrive/GP5/oskelly_imagess/2668086.jpg
5882673 ZIMMERMANN 48013 /content/udrive/MyDrive/GP5/oskelly_imagess/5882673.jpg
3474562 ETRO 89000 /content/udrive/MyDrive/GP5/oskelly_imagess/3474562.jpg
5922294 DOLCE&GABBANA 52788 /content/udrive/MyDrive/GP5/oskelly_imagess/5922294.jpg
5865950 COURREGES 84427 /content/udrive/MyDrive/GP5/oskelly_imagess/5865950.jpeg
2266880 IRO 74000 /content/udrive/MyDrive/GP5/oskelly_imagess/2266880.jpg
2267762 MCQ ALEXANDER MCQUEEN 49000 /content/udrive/MyDrive/GP5/oskelly_imagess/2267762.jpg
4716921 GIAMBATTISTA VALLI 76000 /content/udrive/MyDrive/GP5/oskelly_imagess/4716921.jpeg
1242916 JOSEPH 47000 /content/udrive/MyDrive/GP5/oskelly_imagess/1242916.jpg
1540787 ISABEL MARANT 47000 /content/udrive/MyDrive/GP5/oskelly_imagess/1540787.jpg
1540277 VALENTINO 127000 /content/udrive/MyDrive/GP5/oskelly_imagess/1540277.jpg
1932937 HELMUT LANG 47000 /content/udrive/MyDrive/GP5/oskelly_imagess/1932937.jpg
2138059 CASABLANCA 87000 /content/udrive/MyDrive/GP5/oskelly_imagess/2138059.jpg
1241133 DOLCE&GABBANA 64000 /content/udrive/MyDrive/GP5/oskelly_imagess/1241133.jpg
2244068 AGENT PROVOCATEUR 350000 /content/udrive/MyDrive/GP5/oskelly_imagess/2244068.jpg
256875 SAINT LAURENT 87000 /content/udrive/MyDrive/GP5/oskelly_imagess/256875.jpg
1242032 MONCLER 67000 /content/udrive/MyDrive/GP5/oskelly_imagess/1242032.jpg
998265 ALICE+OLIVIA 48000 /content/udrive/MyDrive/GP5/oskelly_imagess/998265.jpg
683268 STELLA MCCARTNEY 47000 /content/udrive/MyDrive/GP5/oskelly_imagess/683268.jpg
998404 IRO 67000 /content/udrive/MyDrive/GP5/oskelly_imagess/998404.jpg
1265585 VIKTOR & ROLF 75000 /content/udrive/MyDrive/GP5/oskelly_imagess/1265585.jpg
1139727 BALENCIAGA 134000 /content/udrive/MyDrive/GP5/oskelly_imagess/1139727.jpg
562494 PRADA 74000 /content/udrive/MyDrive/GP5/oskelly_imagess/562494.jpg
748914 ALEXANDER WANG 57000 /content/udrive/MyDrive/GP5/oskelly_imagess/748914.jpg
5915152 ZIMMERMANN 69332 /content/udrive/MyDrive/GP5/oskelly_imagess/5915152.jpg
5922313 THE ROW 70000 /content/udrive/MyDrive/GP5/oskelly_imagess/5922313.jpg
5888086 ZIMMERMANN 31468 /content/udrive/MyDrive/GP5/oskelly_imagess/5888086.jpeg
4725075 ISABEL MARANT 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/4725075.jpg
4933345 VETEMENTS 11900 /content/udrive/MyDrive/GP5/oskelly_imagess/4933345.jpg
5922293 DOLCE&GABBANA 42128 /content/udrive/MyDrive/GP5/oskelly_imagess/5922293.jpg
4945413 ISABEL MARANT 72000 /content/udrive/MyDrive/GP5/oskelly_imagess/4945413.jpg
5921673 PINKO 13500 /content/udrive/MyDrive/GP5/oskelly_imagess/5921673.jpeg
5922286 DOLCE&GABBANA 42128 /content/udrive/MyDrive/GP5/oskelly_imagess/5922286.jpg
5905518 TOTEME 45881 /content/udrive/MyDrive/GP5/oskelly_imagess/5905518.jpg
4638194 BURBERRY 295000 /content/udrive/MyDrive/GP5/oskelly_imagess/4638194.jpg
5913056 FENDI 101312 /content/udrive/MyDrive/GP5/oskelly_imagess/5913056.jpg
585058 LOUIS VUITTON 289000 /content/udrive/MyDrive/GP5/oskelly_imagess/585058.jpeg
5560090 ALEXANDER MCQUEEN 60000 /content/udrive/MyDrive/GP5/oskelly_imagess/5560090.jpg
5130440 BALENCIAGA 45000 /content/udrive/MyDrive/GP5/oskelly_imagess/5130440.jpg
5560019 3.1 PHILLIP LIM 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/5560019.jpg
958769 RED VALENTINO 60000 /content/udrive/MyDrive/GP5/oskelly_imagess/958769.jpg
5917159 DOLCE&GABBANA 37353 /content/udrive/MyDrive/GP5/oskelly_imagess/5917159.jpg
1124784 BURBERRY 90000 /content/udrive/MyDrive/GP5/oskelly_imagess/1124784.jpg
1113697 ERMANNO SCERVINO 45000 /content/udrive/MyDrive/GP5/oskelly_imagess/1113697.jpg
1113717 DSQUARED2 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/1113717.jpg
1113618 TWIN-SET 32000 /content/udrive/MyDrive/GP5/oskelly_imagess/1113618.jpg
922426 VALENTINO 155000 /content/udrive/MyDrive/GP5/oskelly_imagess/922426.jpg
5913680 FENDI 191880 /content/udrive/MyDrive/GP5/oskelly_imagess/5913680.jpg
2286854 VERSACE 250000 /content/udrive/MyDrive/GP5/oskelly_imagess/2286854.jpeg
1114096 ICEBERG 50000 /content/udrive/MyDrive/GP5/oskelly_imagess/1114096.jpg
5860045 DOLCE&GABBANA 49000 /content/udrive/MyDrive/GP5/oskelly_imagess/5860045.jpg
1113640 WEEKEND MAX MARA 33000 /content/udrive/MyDrive/GP5/oskelly_imagess/1113640.jpg
5559727 AJE 68000 /content/udrive/MyDrive/GP5/oskelly_imagess/5559727.jpg
5915285 MIU MIU 94916 /content/udrive/MyDrive/GP5/oskelly_imagess/5915285.jpg
5559772 'S MAX MARA 68000 /content/udrive/MyDrive/GP5/oskelly_imagess/5559772.jpg
5559758 RED VALENTINO 68000 /content/udrive/MyDrive/GP5/oskelly_imagess/5559758.jpg
5559745 RED VALENTINO 68000 /content/udrive/MyDrive/GP5/oskelly_imagess/5559745.jpg
5913683 FENDI 138580 /content/udrive/MyDrive/GP5/oskelly_imagess/5913683.jpg
5913683 FENDI 138580 /content/udrive/MyDrive/GP5/oskelly_imagess/5913683.jpg
5559882 BRUNELLO CUCINELLI 170000 /content/udrive/MyDrive/GP5/oskelly_imagess/5559882.jpg
5560038 3.1 PHILLIP LIM 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/5560038.jpg
5559923 ETRO 136000 /content/udrive/MyDrive/GP5/oskelly_imagess/5559923.jpg
5559971 PRADA 170000 /content/udrive/MyDrive/GP5/oskelly_imagess/5559971.jpg
5559945 PRADA 120000 /content/udrive/MyDrive/GP5/oskelly_imagess/5559945.jpg
5559997 DIANE VON FURSTENBERG 68000 /content/udrive/MyDrive/GP5/oskelly_imagess/5559997.jpg
5559783 BURBERRY 200000 /content/udrive/MyDrive/GP5/oskelly_imagess/5559783.jpg
5559988 BCBG MAXAZRIA 50000 /content/udrive/MyDrive/GP5/oskelly_imagess/5559988.jpg
5560054 CAVALLI CLASS 50000 /content/udrive/MyDrive/GP5/oskelly_imagess/5560054.jpg
5922049 POLO RALPH LAUREN 22940 /content/udrive/MyDrive/GP5/oskelly_imagess/5922049.jpeg
5892820 LIU JO 18079 /content/udrive/MyDrive/GP5/oskelly_imagess/5892820.jpg
5922065 POLO RALPH LAUREN 21320 /content/udrive/MyDrive/GP5/oskelly_imagess/5922065.jpeg
5914640 POLO RALPH LAUREN 24049 /content/udrive/MyDrive/GP5/oskelly_imagess/5914640.jpg
5922045 POLO RALPH LAUREN 19785 /content/udrive/MyDrive/GP5/oskelly_imagess/5922045.jpeg
5922034 POLO RALPH LAUREN 19785 /content/udrive/MyDrive/GP5/oskelly_imagess/5922034.jpeg
5922054 POLO RALPH LAUREN 19785 /content/udrive/MyDrive/GP5/oskelly_imagess/5922054.jpeg
5922060 POLO RALPH LAUREN 19785 /content/udrive/MyDrive/GP5/oskelly_imagess/5922060.jpeg
5916820 POLO RALPH LAUREN 19785 /content/udrive/MyDrive/GP5/oskelly_imagess/5916820.jpeg
5915924 None None /content/udrive/MyDrive/GP5/oskelly_imagess/5915924.jpg
5531951 PINKO 42128 /content/udrive/MyDrive/GP5/oskelly_imagess/5531951.jpg
4706556 SPORTMAX 12000 /content/udrive/MyDrive/GP5/oskelly_imagess/4706556.jpg
3103799 ETRO 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/3103799.jpg
3104337 ETRO 60000 /content/udrive/MyDrive/GP5/oskelly_imagess/3104337.jpg
1232020 BLUMARINE 67200 /content/udrive/MyDrive/GP5/oskelly_imagess/1232020.jpg
1413286 SPORTMAX 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/1413286.jpg
5921479 MAGDA BUTRYM 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921479.jpg
2346047 DOLCE&GABBANA 57000 /content/udrive/MyDrive/GP5/oskelly_imagess/2346047.jpg
2660063 MONCLER 57000 /content/udrive/MyDrive/GP5/oskelly_imagess/2660063.jpg
5852375 SACAI 135424 /content/udrive/MyDrive/GP5/oskelly_imagess/5852375.jpg
5760192 J.W.ANDERSON 52788 /content/udrive/MyDrive/GP5/oskelly_imagess/5760192.jpg
2595379 DOLCE&GABBANA 90000 /content/udrive/MyDrive/GP5/oskelly_imagess/2595379.jpg
960109 ELISABETTA FRANCHI 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/960109.jpg
5759420 ETRO 44772 /content/udrive/MyDrive/GP5/oskelly_imagess/5759420.jpg
2694206 MONCLER 65000 /content/udrive/MyDrive/GP5/oskelly_imagess/2694206.jpg
4362167 JOHN RICHMOND 50000 /content/udrive/MyDrive/GP5/oskelly_imagess/4362167.jpg
5759444 MAISON MARGIELA 129028 /content/udrive/MyDrive/GP5/oskelly_imagess/5759444.jpg
4909390 GIUSEPPE DI MORABITO 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/4909390.jpg
4957633 GIVENCHY 120000 /content/udrive/MyDrive/GP5/oskelly_imagess/4957633.jpeg
4909459 GIUSEPPE DI MORABITO 80000 /content/udrive/MyDrive/GP5/oskelly_imagess/4909459.jpg
5302165 PHILIPP PLEIN 130000 /content/udrive/MyDrive/GP5/oskelly_imagess/5302165.jpg
4909479 GIUSEPPE DI MORABITO 100000 /content/udrive/MyDrive/GP5/oskelly_imagess/4909479.jpg
5894638 ALEXANDER WANG 63448 /content/udrive/MyDrive/GP5/oskelly_imagess/5894638.jpg
3861986 SAINT LAURENT 100000 /content/udrive/MyDrive/GP5/oskelly_imagess/3861986.jpg
5831515 CHROME HEARTS 70000 /content/udrive/MyDrive/GP5/oskelly_imagess/5831515.jpg
5759716 MOSCHINO 22429 /content/udrive/MyDrive/GP5/oskelly_imagess/5759716.jpg
5919975 GIULIANA TESO 600000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919975.jpg
5921145 CHRISTIAN DIOR 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921145.jpg
5921325 ZIMMERMANN 28580 /content/udrive/MyDrive/GP5/oskelly_imagess/5921325.jpg
5921361 SELF-PORTRAIT 100000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921361.jpg
5921139 BRUNELLO CUCINELLI 45000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921139.jpg
5921397 ALEXANDER TEREKHOV 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921397.jpg
5921421 KENZO 37000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921421.jpg
5914430 MAX&CO 13000 /content/udrive/MyDrive/GP5/oskelly_imagess/5914430.jpg
5832237 VINCE 17000 /content/udrive/MyDrive/GP5/oskelly_imagess/5832237.jpg
5921150 POLO RALPH LAUREN 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921150.jpg
5920229 SAGA 290000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920229.jpg
5921140 POLO RALPH LAUREN 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921140.jpg
5921007 DOLCE&GABBANA 125000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921007.jpg
5920706 ISABEL MARANT ETOILE 45000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920706.jpg
5921129 CHRISTIAN DIOR 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921129.jpg
5920690 FALCONERI 146670 /content/udrive/MyDrive/GP5/oskelly_imagess/5920690.jpg
5921252 12 STOREEZ 10990 /content/udrive/MyDrive/GP5/oskelly_imagess/5921252.jpg
5658510 SELF-PORTRAIT 26786 /content/udrive/MyDrive/GP5/oskelly_imagess/5658510.jpg
5921126 ANINE BING 15000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921126.jpg
5759402 MOSCHINO 22429 /content/udrive/MyDrive/GP5/oskelly_imagess/5759402.jpg
5893681 CHRISTIAN DIOR 75000 /content/udrive/MyDrive/GP5/oskelly_imagess/5893681.jpg
5921249 HELMUT LANG 10990 /content/udrive/MyDrive/GP5/oskelly_imagess/5921249.jpg
5861008 SEA NYC 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/5861008.jpg
5921303 HERMES 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921303.jpg
5921423 CAVALLI CLASS 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921423.jpg
5921148 ERMANNO SCERVINO 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921148.jpg
5920652 ETRO 15000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920652.jpg
5921024 OFF-WHITE 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921024.jpg
5921331 WEEKEND MAX MARA 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921331.jpg
1999105 ARMY YVES SALOMON 165000 /content/udrive/MyDrive/GP5/oskelly_imagess/1999105.jpg
5921137 BRUNELLO CUCINELLI 45000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921137.jpg
5921312 CHANEL 55000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921312.jpg
5921347 PHILIPP PLEIN 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921347.jpg
5919936 WEEKEND MAX MARA 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919936.jpg
5921248 OFF-WHITE 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921248.jpg
5921415 MARQUES' ALMEIDA 59000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921415.jpg
5919973 GUCCI 196000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919973.jpg
5921280 IRO 46000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921280.jpg
5921398 GIORGIO ARMANI 49500 /content/udrive/MyDrive/GP5/oskelly_imagess/5921398.jpg
5921006 PRADA 500000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921006.jpg
5921430 ANN DEMEULEMEESTER 137000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921430.jpg
5921305 VALENTINO 46670 /content/udrive/MyDrive/GP5/oskelly_imagess/5921305.jpg
5921274 SAINT LAURENT 300000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921274.jpg
5920169 LORO PIANA 400000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920169.jpg
5921039 CHANEL 220000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921039.jpg
5921310 BAPE 36000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921310.jpg
5921285 GUCCI 28580 /content/udrive/MyDrive/GP5/oskelly_imagess/5921285.jpg
5921339 CHRISTIAN DIOR 28000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921339.jpg
5920221 PINKO 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920221.jpg
5921297 BCBG MAXAZRIA 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921297.jpg
5921391 ALO YOGA 17900 /content/udrive/MyDrive/GP5/oskelly_imagess/5921391.jpg
5920908 ALEXANDER MCQUEEN 85000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920908.jpg
5921168 GUCCI 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921168.jpg
5921433 DOLCE&GABBANA 59000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921433.jpg
5921250 CHRISTIAN DIOR 95000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921250.jpg
5921447 ROTATE 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921447.jpg
5921357 STELLA MCCARTNEY 80000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921357.jpg
5921356 ARMANI COLLEZIONI 60000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921356.jpg
5921364 STELLA MCCARTNEY 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921364.jpg
5920748 CP COMPANY 12000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920748.jpg
5920135 KITH 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920135.jpg
5920920 SPORTMAX 160000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920920.jpg
5919908 WALK OF SHAME 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919908.jpg
5920136 HELMUT LANG 19900 /content/udrive/MyDrive/GP5/oskelly_imagess/5920136.jpg
5920600 CHRISTIAN DIOR 130000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920600.jpg
5919939 CHRISTIAN DIOR 240000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919939.jpg
5919995 PINKO 45000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919995.jpg
5920927 SPORTMAX 200000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920927.jpg
5919941 JIL SANDER 11500 /content/udrive/MyDrive/GP5/oskelly_imagess/5919941.jpg
5920637 CHRISTIAN DIOR 50000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920637.jpg
5920008 VETEMENTS 55000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920008.jpg
5759424 BRUNELLO CUCINELLI 106429 /content/udrive/MyDrive/GP5/oskelly_imagess/5759424.jpg
5920130 GUCCI 25900 /content/udrive/MyDrive/GP5/oskelly_imagess/5920130.jpg
5919955 BRUNELLO CUCINELLI 150000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919955.jpg
5919998 JOHN RICHMOND 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919998.jpg
5919840 ARMANI EXCHANGE 13000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919840.jpg
5920256 LOVE MOSCHINO 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920256.jpg
5920771 THE FRANKIE SHOP 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920771.jpg
5920609 POLO RALPH LAUREN 28000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920609.jpg
5920125 KITH 16000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920125.jpg
5920184 CAROLINA HERRERA 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920184.jpg
5919925 R13 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919925.jpg
5920666 MAX MARA STUDIO 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920666.jpg
5919855 CHRISTIAN DIOR 350000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919855.jpg
5920220 CHANEL 80000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920220.jpg
5920203 CHRISTIAN DIOR 130000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920203.jpg
5914809 CHLOE 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/5914809.jpg
5920924 SPORTMAX 160000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920924.jpg
5920643 DOLCE&GABBANA 50000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920643.jpg
5920157 SCHIAPARELLI 99000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920157.jpg
5920233 ARMANI EXCHANGE 15000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920233.jpg
5917346 SPORTMAX 13000 /content/udrive/MyDrive/GP5/oskelly_imagess/5917346.jpg
5920123 BURBERRY 25900 /content/udrive/MyDrive/GP5/oskelly_imagess/5920123.jpg
5920712 DOLCE&GABBANA 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920712.jpg
5920145 BALMAIN 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920145.jpg
5920617 HERMES 125000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920617.jpg
5920901 DOLCE&GABBANA 39500 /content/udrive/MyDrive/GP5/oskelly_imagess/5920901.jpg
5920636 HERMES 80000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920636.jpg
5919953 PRADA 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919953.jpg
5919769 RASARIO 120000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919769.jpg
5920611 PRADA 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920611.jpg
5920182 KITH 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920182.jpg
5920685 MAX MARA 27180 /content/udrive/MyDrive/GP5/oskelly_imagess/5920685.jpg
5688480 MM6 MAISON MARGIELA 20357 /content/udrive/MyDrive/GP5/oskelly_imagess/5688480.jpg
5920620 GIVENCHY 18000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920620.jpg
5920871 CHROME HEARTS 275000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920871.jpg
5884321 ALO YOGA 23500 /content/udrive/MyDrive/GP5/oskelly_imagess/5884321.jpg
5759028 STELLA MCCARTNEY 29607 /content/udrive/MyDrive/GP5/oskelly_imagess/5759028.jpg
5759224 DSQUARED2 48013 /content/udrive/MyDrive/GP5/oskelly_imagess/5759224.jpg
5908437 ALEXANDER MCQUEEN 276136 /content/udrive/MyDrive/GP5/oskelly_imagess/5908437.jpg
5758855 MAISON MARGIELA 52277 /content/udrive/MyDrive/GP5/oskelly_imagess/5758855.jpg
5908440 ALEXANDER MCQUEEN 105576 /content/udrive/MyDrive/GP5/oskelly_imagess/5908440.jpg
5758641 DSQUARED2 30957 /content/udrive/MyDrive/GP5/oskelly_imagess/5758641.jpg
5887949 ZIMMERMANN 135936 /content/udrive/MyDrive/GP5/oskelly_imagess/5887949.jpeg
5914677 SAINT LAURENT 191880 /content/udrive/MyDrive/GP5/oskelly_imagess/5914677.jpg
2388455 JUST CAVALLI 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/2388455.jpg
5916058 GUCCI 88435 /content/udrive/MyDrive/GP5/oskelly_imagess/5916058.jpg
5915967 VALENTINO 212688 /content/udrive/MyDrive/GP5/oskelly_imagess/5915967.jpeg
2932402 VERSACE 42000 /content/udrive/MyDrive/GP5/oskelly_imagess/2932402.jpg
5915939 GUCCI 167916 /content/udrive/MyDrive/GP5/oskelly_imagess/5915939.jpeg
5630281 ZIMMERMANN 175932 /content/udrive/MyDrive/GP5/oskelly_imagess/5630281.jpeg
5910093 SELF-PORTRAIT 57564 /content/udrive/MyDrive/GP5/oskelly_imagess/5910093.jpg
5915959 VALENTINO 166807 /content/udrive/MyDrive/GP5/oskelly_imagess/5915959.jpeg
5910086 ZIMMERMANN 52788 /content/udrive/MyDrive/GP5/oskelly_imagess/5910086.jpg
5910112 ZIMMERMANN 71976 /content/udrive/MyDrive/GP5/oskelly_imagess/5910112.jpg
5915242 FENDI 133292 /content/udrive/MyDrive/GP5/oskelly_imagess/5915242.jpg
5910078 GIVENCHY 149240 /content/udrive/MyDrive/GP5/oskelly_imagess/5910078.jpg
5895367 STELLA MCCARTNEY 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5895367.jpg
5895350 HUGO BOSS 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5895350.jpg

In [ ]:
data = pd.DataFrame(all_items)
data.to_excel('all_items_700-1500_with_images.xlsx', index=False)
data.head()

,Oskelly ID,url,Размер,Раздел,Категория,Бренд,Материал одежды,Цвет,Состояние товара,Продавец,...,Скидка,Описание,Название,Состояние,image_url,image_path,Посадка,Винтаж,Материал джинсов,Модель
0,3598842,https://oskelly.ru/products/yubka-midi-johanna...,INT XS,Женское,Юбки миди,JOHANNA ORTIZ,Другое,Зеленый,Новое с биркой,Частный продавец,...,-54%,🌿🐆🌿🐆\n\nРоскошная юбка от Johanna Ortiz с прин...,JOHANNA ORTIZЗеленая юбка мидиЗеленая юбка миди,Новое с биркой,https://static.cdn.oskelly.ru/product/3598842/...,/content/udrive/MyDrive/GP5/oskelly_imagess/35...,NaN,NaN,NaN,NaN
1,2334055,https://oskelly.ru/products/mayka-alexander-mc...,INT S,Женское,Майки,ALEXANDER MCQUEEN,Другое,Хаки,Новое с биркой,Частный продавец,...,-47%,💫💫\n\nЭлегантный укороченный трикотажный топ с...,ALEXANDER MCQUEENХаки майкаХаки майка,Новое с биркой,https://static.cdn.oskelly.ru/product/2334055/...,/content/udrive/MyDrive/GP5/oskelly_imagess/23...,NaN,NaN,NaN,NaN
2,5921710,https://oskelly.ru/products/dzhemper--sviter-p...,INT M,Женское,Джемперы и свитеры,POLO RALPH LAUREN,Хлопок,Голубой,Новое с биркой,Частный продавец,...,NaN,Шикарный свитер из хлопка с легендарным медвед...,POLO RALPH LAURENГолубой хлопковый джемпер / с...,Новое с биркой,https://static.cdn.oskelly.ru/product/5921710/...,/content/udrive/MyDrive/GP5/oskelly_imagess/59...,NaN,NaN,NaN,NaN
3,2139948,https://oskelly.ru/products/bluzy-zimmermann-n...,INT S,Женское,Блузы,ZIMMERMANN,Хлопок,Желтый,Новое с биркой,Частный продавец,...,-36%,☘️🌱🌼🌱☘️\n\nБлузка с нежным цветочным принтом \...,ZIMMERMANNЖелтая хлопковая блузыЖелтая хлопков...,Новое с биркой,https://static.cdn.oskelly.ru/product/2139948/...,/content/udrive/MyDrive/GP5/oskelly_imagess/21...,NaN,NaN,NaN,NaN
4,5918765,https://oskelly.ru/products/zhaketpidzhak-gucc...,IT 44,Женское,Жакеты и пиджаки,GUCCI,Хлопок,Синий,Новое с биркой,Бутик,...,-29%,GG dedim blazer. Exterior: 100% Cotton,GUCCIСиний хлопковый жакет/пиджакСиний хлопков...,Новое с биркой,https://static.cdn.oskelly.ru/product/5918765/...,/content/udrive/MyDrive/GP5/oskelly_imagess/59...,NaN,NaN,NaN,NaN

In [ ]:
all_items = []

for i in range(1500, 2200):
  url = 'https://oskelly.ru' + items.iloc[i, 0]
  oskelly = requests.get(url, headers=headers)

  if oskelly.status_code == 200:
    soup = BeautifulSoup(oskelly.text, 'html')
    item = {}

    item_id = items.iloc[i, 0].split('-')[-1]
    item['Oskelly ID'] = item_id
    item['url'] = url

    for elem in soup.find_all('li', class_='osk-product-attributes__item'):
      name_elem = elem.find('span', class_='osk-product-attributes__item-name')
      value_elem = elem.find('span', class_='osk-product-attributes__item-value')

      if name_elem and value_elem:
        category = name_elem.text.strip()
        value = value_elem.text.strip()
        item[category] = value

    price = soup.find('span', class_='osk-product__rrpPrice')
    if price:
      item['Цена'] = price.text.replace('\xa0', '').replace('₽', '').strip()

    discount = soup.find('span', class_='osk-product__discount')
    if discount:
      item['Скидка'] = discount.text.strip()

    price2 = soup.find('span', class_='osk-product__price')
    if price2 and 'Цена' not in item:
      item['Цена'] = price2.text.replace('\xa0', '').replace('₽', '').strip()


    description = soup.find('div', class_='osk-product-seller__description')
    if description:
      item['Описание'] = description.text.strip()


    brand = soup.find('a', class_='osk-product__brand')
    if brand:
      item['Бренд'] = brand.text.strip()


    title = soup.find('h1', class_='osk-product__title')
    if title:
      item['Название'] = title.text.strip()


    condition = soup.find('div', class_='osk-product__condition')
    if condition:
      item['Состояние'] = condition.text.strip()


    image_url = get_main_product_image_url(soup)
    image_path = download_main_product_image(image_url=image_url,item_id=item_id,images_dir=images_dir)

    item['image_url'] = image_url
    item['image_path'] = image_path

    all_items.append(item)

    print(item_id, item.get('Бренд'), item.get('Цена'), image_path)

  time.sleep(0.5)

5829074 VETEMENTS 75000 /content/udrive/MyDrive/GP5/oskelly_imagess/5829074.jpg
5708655 Melissa 22860 /content/udrive/MyDrive/GP5/oskelly_imagess/5708655.jpg
5920954 LOUIS VUITTON 32860 /content/udrive/MyDrive/GP5/oskelly_imagess/5920954.jpg
1690337 MIU MIU 80000 /content/udrive/MyDrive/GP5/oskelly_imagess/1690337.jpg
5859263 POLO RALPH LAUREN 36000 /content/udrive/MyDrive/GP5/oskelly_imagess/5859263.jpeg
5921041 CHANEL 430000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921041.jpeg
1566096 MISSONI 200000 /content/udrive/MyDrive/GP5/oskelly_imagess/1566096.jpg
4953255 PRADA 125000 /content/udrive/MyDrive/GP5/oskelly_imagess/4953255.jpg
2042825 WOLFORD 44000 /content/udrive/MyDrive/GP5/oskelly_imagess/2042825.jpg
5445888 SPORTY AND RICH 28000 /content/udrive/MyDrive/GP5/oskelly_imagess/5445888.jpg
5867630 DOLCE&GABBANA 98000 /content/udrive/MyDrive/GP5/oskelly_imagess/5867630.jpg
5919946 ALO YOGA 16200 /content/udrive/MyDrive/GP5/oskelly_imagess/5919946.jpeg
5871273 EMPORIO ARMANI 19188 /content/udrive/MyDrive/GP5/oskelly_imagess/5871273.jpg
5920154 ACNE STUDIOS 65000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920154.jpeg
5871321 EMPORIO ARMANI 39485 /content/udrive/MyDrive/GP5/oskelly_imagess/5871321.jpg
2381520 GUCCI 145000 /content/udrive/MyDrive/GP5/oskelly_imagess/2381520.jpg
5910826 DOLCE&GABBANA 63448 /content/udrive/MyDrive/GP5/oskelly_imagess/5910826.jpg
5920199 LOUIS VUITTON 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920199.jpeg
5072995 MAX MARA STUDIO 112000 /content/udrive/MyDrive/GP5/oskelly_imagess/5072995.jpg
1619406 PINKO 18060 /content/udrive/MyDrive/GP5/oskelly_imagess/1619406.jpg
4448828 POLO RALPH LAUREN 18950 /content/udrive/MyDrive/GP5/oskelly_imagess/4448828.jpg
5886524 POLO RALPH LAUREN 18220 /content/udrive/MyDrive/GP5/oskelly_imagess/5886524.jpeg
4448483 POLO RALPH LAUREN 38740 /content/udrive/MyDrive/GP5/oskelly_imagess/4448483.jpg
5919848 ALO YOGA 15500 /content/udrive/MyDrive/GP5/oskelly_imagess/5919848.jpeg
5919859 ALO YOGA 17900 /content/udrive/MyDrive/GP5/oskelly_imagess/5919859.jpeg
5919852 ALO YOGA 17900 /content/udrive/MyDrive/GP5/oskelly_imagess/5919852.jpeg
5871301 EMPORIO ARMANI 29848 /content/udrive/MyDrive/GP5/oskelly_imagess/5871301.jpg
5919851 JACQUEMUS 18000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919851.jpg
1592101 CALVIN KLEIN JEANS 16000 /content/udrive/MyDrive/GP5/oskelly_imagess/1592101.jpg
5919872 ALO YOGA 14900 /content/udrive/MyDrive/GP5/oskelly_imagess/5919872.jpeg
5919870 ALO YOGA 13900 /content/udrive/MyDrive/GP5/oskelly_imagess/5919870.jpeg
5919942 ALO YOGA 13900 /content/udrive/MyDrive/GP5/oskelly_imagess/5919942.jpeg
5359570 MARC JACOBS 25520 /content/udrive/MyDrive/GP5/oskelly_imagess/5359570.jpg
1619450 MICHAEL MICHAEL KORS 13660 /content/udrive/MyDrive/GP5/oskelly_imagess/1619450.jpg
5910809 STELLA MCCARTNEY 84256 /content/udrive/MyDrive/GP5/oskelly_imagess/5910809.jpg
1231569 MICHAEL MICHAEL KORS 30500 /content/udrive/MyDrive/GP5/oskelly_imagess/1231569.jpg
5921040 CHANEL 200000 /content/udrive/MyDrive/GP5/oskelly_imagess/5921040.jpeg
5285080 GANNI 13000 /content/udrive/MyDrive/GP5/oskelly_imagess/5285080.jpg
5917285 SAINT LAURENT 65000 /content/udrive/MyDrive/GP5/oskelly_imagess/5917285.jpg
3908705 CHRISTIAN DIOR 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/3908705.jpg
5901000 VETEMENTS 33000 /content/udrive/MyDrive/GP5/oskelly_imagess/5901000.jpeg
4067477 SAINT LAURENT 54000 /content/udrive/MyDrive/GP5/oskelly_imagess/4067477.jpg
5912799 CELINE 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/5912799.jpg
3971526 CHRISTIAN DIOR 39000 /content/udrive/MyDrive/GP5/oskelly_imagess/3971526.jpg
3971611 CHRISTIAN DIOR 41000 /content/udrive/MyDrive/GP5/oskelly_imagess/3971611.jpg
4846650 MIU MIU 26000 /content/udrive/MyDrive/GP5/oskelly_imagess/4846650.jpg
5849016 PRADA 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/5849016.jpeg
5554469 GUCCI 60000 /content/udrive/MyDrive/GP5/oskelly_imagess/5554469.jpeg
5298187 VERSACE 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5298187.jpg
3670963 SELF-PORTRAIT 130000 /content/udrive/MyDrive/GP5/oskelly_imagess/3670963.jpg
4840184 VERSACE 22860 /content/udrive/MyDrive/GP5/oskelly_imagess/4840184.jpg
5241079 SAINT LAURENT 340096 /content/udrive/MyDrive/GP5/oskelly_imagess/5241079.jpeg
5916337 VERSACE 11430 /content/udrive/MyDrive/GP5/oskelly_imagess/5916337.jpg
4662023 AGENT PROVOCATEUR 17000 /content/udrive/MyDrive/GP5/oskelly_imagess/4662023.jpg
5915076 MAX MARA 245179 /content/udrive/MyDrive/GP5/oskelly_imagess/5915076.jpeg
5352765 PRADA 522339 /content/udrive/MyDrive/GP5/oskelly_imagess/5352765.webp
5352662 PRADA 79992 /content/udrive/MyDrive/GP5/oskelly_imagess/5352662.jpeg
5908340 KIDSUPER 39000 /content/udrive/MyDrive/GP5/oskelly_imagess/5908340.jpg
533960 ALEXANDER WANG 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/533960.jpg
2126741 ALEXANDER WANG 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/2126741.jpg
4228875 NO. 21 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/4228875.jpg
70651 P.A.R.O.S.H. 24000 /content/udrive/MyDrive/GP5/oskelly_imagess/70651.jpg
2271465 CELINE 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/2271465.jpg
3669976 BALMAIN 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/3669976.jpg
5504058 MISSONI 55000 /content/udrive/MyDrive/GP5/oskelly_imagess/5504058.jpeg
5826214 SUPREME 34650 /content/udrive/MyDrive/GP5/oskelly_imagess/5826214.jpg
5826225 STUSSY 13320 /content/udrive/MyDrive/GP5/oskelly_imagess/5826225.jpg
5615449 FEAR OF GOD ESSENTIALS 28060 /content/udrive/MyDrive/GP5/oskelly_imagess/5615449.jpg
5615408 FEAR OF GOD ESSENTIALS 14700 /content/udrive/MyDrive/GP5/oskelly_imagess/5615408.jpg
5615414 FEAR OF GOD ESSENTIALS 14700 /content/udrive/MyDrive/GP5/oskelly_imagess/5615414.jpg
5379529 SUPREME 27690 /content/udrive/MyDrive/GP5/oskelly_imagess/5379529.jpg
5411476 SUPREME 11480 /content/udrive/MyDrive/GP5/oskelly_imagess/5411476.jpg
5266282 STUSSY 13300 /content/udrive/MyDrive/GP5/oskelly_imagess/5266282.jpg
5826188 POLO RALPH LAUREN 26090 /content/udrive/MyDrive/GP5/oskelly_imagess/5826188.jpg
5451051 'S MAX MARA 17500 /content/udrive/MyDrive/GP5/oskelly_imagess/5451051.jpg
5678683 POLO RALPH LAUREN 27880 /content/udrive/MyDrive/GP5/oskelly_imagess/5678683.jpg
5424857 STONE ISLAND 83440 /content/udrive/MyDrive/GP5/oskelly_imagess/5424857.jpg
5597074 POLO RALPH LAUREN 37200 /content/udrive/MyDrive/GP5/oskelly_imagess/5597074.jpg
5265965 STUSSY 23080 /content/udrive/MyDrive/GP5/oskelly_imagess/5265965.jpg
5264850 STUSSY 23080 /content/udrive/MyDrive/GP5/oskelly_imagess/5264850.jpg
5480539 LOEWE 56609 /content/udrive/MyDrive/GP5/oskelly_imagess/5480539.jpg
5509435 POLO RALPH LAUREN 37200 /content/udrive/MyDrive/GP5/oskelly_imagess/5509435.jpg
5273036 LOEWE 64520 /content/udrive/MyDrive/GP5/oskelly_imagess/5273036.jpg
5408034 ACNE STUDIOS 75478 /content/udrive/MyDrive/GP5/oskelly_imagess/5408034.jpg
4884149 DRIES VAN NOTEN 70000 /content/udrive/MyDrive/GP5/oskelly_imagess/4884149.jpg
5578549 ALO YOGA 11400 /content/udrive/MyDrive/GP5/oskelly_imagess/5578549.jpg
4077345 SKIMS 11400 /content/udrive/MyDrive/GP5/oskelly_imagess/4077345.jpg
4077237 ALO YOGA 10640 /content/udrive/MyDrive/GP5/oskelly_imagess/4077237.jpg
4077312 ALO YOGA 19010 /content/udrive/MyDrive/GP5/oskelly_imagess/4077312.jpg
4768012 SKIMS 17740 /content/udrive/MyDrive/GP5/oskelly_imagess/4768012.jpg
3766074 STUSSY 11960 /content/udrive/MyDrive/GP5/oskelly_imagess/3766074.jpg
5006248 POLO RALPH LAUREN 31054 /content/udrive/MyDrive/GP5/oskelly_imagess/5006248.jpg
3784792 MIU MIU 147722 /content/udrive/MyDrive/GP5/oskelly_imagess/3784792.jpg
3843795 ACNE STUDIOS 34925 /content/udrive/MyDrive/GP5/oskelly_imagess/3843795.jpg
3768198 MIU MIU 96612 /content/udrive/MyDrive/GP5/oskelly_imagess/3768198.jpg
5153088 NANUSHKA 66700 /content/udrive/MyDrive/GP5/oskelly_imagess/5153088.jpg
4047713 None None /content/udrive/MyDrive/GP5/oskelly_imagess/4047713.jpg
3761467 LOEWE 117530 /content/udrive/MyDrive/GP5/oskelly_imagess/3761467.jpg
4513262 ADIDAS 15960 /content/udrive/MyDrive/GP5/oskelly_imagess/4513262.jpg
4307224 BALENCIAGA 71165 /content/udrive/MyDrive/GP5/oskelly_imagess/4307224.jpg
3903162 MIU MIU 279269 /content/udrive/MyDrive/GP5/oskelly_imagess/3903162.jpg
3861072 SUPREME 35360 /content/udrive/MyDrive/GP5/oskelly_imagess/3861072.jpg
3664027 ACNE STUDIOS 37200 /content/udrive/MyDrive/GP5/oskelly_imagess/3664027.jpg
3664019 ACNE STUDIOS 47990 /content/udrive/MyDrive/GP5/oskelly_imagess/3664019.jpg
3364736 STUSSY 33760 /content/udrive/MyDrive/GP5/oskelly_imagess/3364736.jpg
3034445 BURBERRY 154113 /content/udrive/MyDrive/GP5/oskelly_imagess/3034445.jpg
5004141 POLO RALPH LAUREN 35706 /content/udrive/MyDrive/GP5/oskelly_imagess/5004141.jpeg
5645513 ROLAND MOURET 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/5645513.jpg
5861475 DOLCE&GABBANA 87600 /content/udrive/MyDrive/GP5/oskelly_imagess/5861475.jpeg
5408843 ACNE STUDIOS 46360 /content/udrive/MyDrive/GP5/oskelly_imagess/5408843.jpg
2914066 ALO YOGA 11400 /content/udrive/MyDrive/GP5/oskelly_imagess/2914066.jpg
5658501 SKIMS 11000 /content/udrive/MyDrive/GP5/oskelly_imagess/5658501.jpg
5465695 LOUIS VUITTON 98800 /content/udrive/MyDrive/GP5/oskelly_imagess/5465695.jpeg
4936206 CELINE 64033 /content/udrive/MyDrive/GP5/oskelly_imagess/4936206.jpg
3878204 YEEZY 23080 /content/udrive/MyDrive/GP5/oskelly_imagess/3878204.jpg
4650937 THE NORTH FACE 28420 /content/udrive/MyDrive/GP5/oskelly_imagess/4650937.jpg
3014371 FEAR OF GOD ESSENTIALS 11570 /content/udrive/MyDrive/GP5/oskelly_imagess/3014371.jpg
2735629 MIU MIU 68374 /content/udrive/MyDrive/GP5/oskelly_imagess/2735629.jpg
2387712 VERSUS VERSACE 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/2387712.jpg
2735566 MIU MIU 176904 /content/udrive/MyDrive/GP5/oskelly_imagess/2735566.jpg
3096254 BALENCIAGA 44720 /content/udrive/MyDrive/GP5/oskelly_imagess/3096254.jpg
2910676 MIU MIU 170510 /content/udrive/MyDrive/GP5/oskelly_imagess/2910676.jpg
2735494 MIU MIU 98800 /content/udrive/MyDrive/GP5/oskelly_imagess/2735494.jpg
4155372 ZADIG & VOLTAIRE 55000 /content/udrive/MyDrive/GP5/oskelly_imagess/4155372.jpg
5412005 STUSSY 11570 /content/udrive/MyDrive/GP5/oskelly_imagess/5412005.jpg
3366982 SUPREME 31260 /content/udrive/MyDrive/GP5/oskelly_imagess/3366982.jpg
5603111 CHANEL 200000 /content/udrive/MyDrive/GP5/oskelly_imagess/5603111.jpg
5258019 LOUIS VUITTON 287442 /content/udrive/MyDrive/GP5/oskelly_imagess/5258019.jpg
2277190 BOUTIQUE MOSCHINO 59000 /content/udrive/MyDrive/GP5/oskelly_imagess/2277190.jpg
5861809 POLO RALPH LAUREN 27860 /content/udrive/MyDrive/GP5/oskelly_imagess/5861809.jpeg
5428475 LOUIS VUITTON 90113 /content/udrive/MyDrive/GP5/oskelly_imagess/5428475.jpg
4603163 HERNO 100000 /content/udrive/MyDrive/GP5/oskelly_imagess/4603163.jpg
4341198 Melissa 23580 /content/udrive/MyDrive/GP5/oskelly_imagess/4341198.jpg
4724489 SANDRO 12000 /content/udrive/MyDrive/GP5/oskelly_imagess/4724489.jpg
3362165 STUSSY 10788 /content/udrive/MyDrive/GP5/oskelly_imagess/3362165.jpg
5585949 CHANEL 82670 /content/udrive/MyDrive/GP5/oskelly_imagess/5585949.jpg
3013811 FEAR OF GOD ESSENTIALS 17561 /content/udrive/MyDrive/GP5/oskelly_imagess/3013811.png
3877133 YEEZY 12927 /content/udrive/MyDrive/GP5/oskelly_imagess/3877133.jpg
4835076 CHANEL 21430 /content/udrive/MyDrive/GP5/oskelly_imagess/4835076.jpg
5569532 VALENTINO 25720 /content/udrive/MyDrive/GP5/oskelly_imagess/5569532.jpg
4710957 CELINE 41340 /content/udrive/MyDrive/GP5/oskelly_imagess/4710957.jpg
4816469 VALENTINO 70000 /content/udrive/MyDrive/GP5/oskelly_imagess/4816469.jpg
3646228 ZIMMERMANN 15000 /content/udrive/MyDrive/GP5/oskelly_imagess/3646228.jpg
4737629 CHLOE 21430 /content/udrive/MyDrive/GP5/oskelly_imagess/4737629.jpg
5858821 CHANEL 46670 /content/udrive/MyDrive/GP5/oskelly_imagess/5858821.jpeg
5458041 CHRISTIAN DIOR 17150 /content/udrive/MyDrive/GP5/oskelly_imagess/5458041.jpg
4738847 CHLOE 68000 /content/udrive/MyDrive/GP5/oskelly_imagess/4738847.jpg
5917804 DOLCE&GABBANA 11430 /content/udrive/MyDrive/GP5/oskelly_imagess/5917804.jpg
5446626 MIU MIU 34000 /content/udrive/MyDrive/GP5/oskelly_imagess/5446626.jpg
3013613 FEAR OF GOD ESSENTIALS 17561 /content/udrive/MyDrive/GP5/oskelly_imagess/3013613.jpg
1127965 FENDI 130000 /content/udrive/MyDrive/GP5/oskelly_imagess/1127965.jpg
950681 PRADA 128000 /content/udrive/MyDrive/GP5/oskelly_imagess/950681.jpeg
869652 JEAN PAUL GAULTIER 56000 /content/udrive/MyDrive/GP5/oskelly_imagess/869652.jpg
5896998 BURBERRY 79000 /content/udrive/MyDrive/GP5/oskelly_imagess/5896998.jpeg
5604456 BLUMARINE 28600 /content/udrive/MyDrive/GP5/oskelly_imagess/5604456.jpg
5604564 BLUMARINE 27400 /content/udrive/MyDrive/GP5/oskelly_imagess/5604564.jpg
5827331 DOLCE&GABBANA 16000 /content/udrive/MyDrive/GP5/oskelly_imagess/5827331.jpg
5499238 CHANEL 22000 /content/udrive/MyDrive/GP5/oskelly_imagess/5499238.jpeg
2438054 POLO RALPH LAUREN 22500 /content/udrive/MyDrive/GP5/oskelly_imagess/2438054.jpg
3902633 DSQUARED2 66700 /content/udrive/MyDrive/GP5/oskelly_imagess/3902633.jpg
5446706 ICEBERG 38600 /content/udrive/MyDrive/GP5/oskelly_imagess/5446706.jpg
1030208 JOHN RICHMOND 28900 /content/udrive/MyDrive/GP5/oskelly_imagess/1030208.jpg
4566363 BIKKEMBERGS 17000 /content/udrive/MyDrive/GP5/oskelly_imagess/4566363.jpg
2496089 DIESEL 36800 /content/udrive/MyDrive/GP5/oskelly_imagess/2496089.jpg
3324140 NO. 21 60500 /content/udrive/MyDrive/GP5/oskelly_imagess/3324140.jpg
4849888 JUICY COUTURE 17000 /content/udrive/MyDrive/GP5/oskelly_imagess/4849888.jpg
5672404 MSGM 48900 /content/udrive/MyDrive/GP5/oskelly_imagess/5672404.jpg
5042714 BLUMARINE 22000 /content/udrive/MyDrive/GP5/oskelly_imagess/5042714.jpg
4134464 TWIN-SET 28600 /content/udrive/MyDrive/GP5/oskelly_imagess/4134464.jpg
1240935 ISABEL MARANT ETOILE 47000 /content/udrive/MyDrive/GP5/oskelly_imagess/1240935.jpg
5431803 MAX MARA 46300 /content/udrive/MyDrive/GP5/oskelly_imagess/5431803.jpg
5643582 SKIMS 12000 /content/udrive/MyDrive/GP5/oskelly_imagess/5643582.jpg
5914396 CELINE 69500 /content/udrive/MyDrive/GP5/oskelly_imagess/5914396.jpg
5914419 CELINE 50000 /content/udrive/MyDrive/GP5/oskelly_imagess/5914419.jpg
5909910 IRO 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/5909910.jpeg
5914392 CELINE 99800 /content/udrive/MyDrive/GP5/oskelly_imagess/5914392.jpeg
5914126 CELINE 68900 /content/udrive/MyDrive/GP5/oskelly_imagess/5914126.jpeg
5914356 CELINE 96500 /content/udrive/MyDrive/GP5/oskelly_imagess/5914356.jpeg
5913941 CELINE 85900 /content/udrive/MyDrive/GP5/oskelly_imagess/5913941.jpg
5328065 HUGO BOSS 15000 /content/udrive/MyDrive/GP5/oskelly_imagess/5328065.jpg
5209196 LOUIS VUITTON 67000 /content/udrive/MyDrive/GP5/oskelly_imagess/5209196.jpeg
5330998 HUGO 49900 /content/udrive/MyDrive/GP5/oskelly_imagess/5330998.jpg
5331024 HUGO BOSS 49900 /content/udrive/MyDrive/GP5/oskelly_imagess/5331024.jpg
5919385 SPORTMAX 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919385.jpg
4763588 GOLDEN GOOSE 375000 /content/udrive/MyDrive/GP5/oskelly_imagess/4763588.jpg
931889 CHRISTIAN DIOR 45000 /content/udrive/MyDrive/GP5/oskelly_imagess/931889.jpg
5732990 CHRISTIAN DIOR 137900 /content/udrive/MyDrive/GP5/oskelly_imagess/5732990.jpg
5732991 CHRISTIAN DIOR 27000 /content/udrive/MyDrive/GP5/oskelly_imagess/5732991.jpg
5884038 KARL LAGERFELD 22000 /content/udrive/MyDrive/GP5/oskelly_imagess/5884038.jpeg
5583649 None None /content/udrive/MyDrive/GP5/oskelly_imagess/5583649.jpg
4447930 AURALEE 17000 /content/udrive/MyDrive/GP5/oskelly_imagess/4447930.jpg
5910834 DOLCE&GABBANA 74108 /content/udrive/MyDrive/GP5/oskelly_imagess/5910834.jpg
5871303 EMPORIO ARMANI 46904 /content/udrive/MyDrive/GP5/oskelly_imagess/5871303.jpg
5910839 STELLA MCCARTNEY 212176 /content/udrive/MyDrive/GP5/oskelly_imagess/5910839.jpg
4518601 GUCCI 220000 /content/udrive/MyDrive/GP5/oskelly_imagess/4518601.jpg
5920162 BLUMARINE 11000 /content/udrive/MyDrive/GP5/oskelly_imagess/5920162.jpeg
5915500 VALENTINO 309139 /content/udrive/MyDrive/GP5/oskelly_imagess/5915500.jpg
5915501 STELLA MCCARTNEY 101312 /content/udrive/MyDrive/GP5/oskelly_imagess/5915501.jpg
5256379 LOEWE 175000 /content/udrive/MyDrive/GP5/oskelly_imagess/5256379.jpg
5910840 DOLCE&GABBANA 50656 /content/udrive/MyDrive/GP5/oskelly_imagess/5910840.jpg
5919813 12 STOREEZ 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919813.jpg
5919797 FENDI 37000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919797.jpg
5919762 MAX MARA 27700 /content/udrive/MyDrive/GP5/oskelly_imagess/5919762.jpg
5919720 RED VALENTINO 12000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919720.jpg
5919694 ZIMMERMANN 84000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919694.jpg
5919704 WOLFORD 13900 /content/udrive/MyDrive/GP5/oskelly_imagess/5919704.jpg
5919766 DOLCE&GABBANA 12000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919766.jpg
5919691 12 STOREEZ 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919691.jpg
5919423 ZIMMERMANN 76000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919423.jpg
5915852 ISABEL MARANT ETOILE 23540 /content/udrive/MyDrive/GP5/oskelly_imagess/5915852.jpeg
5919490 AVAVAV 28580 /content/udrive/MyDrive/GP5/oskelly_imagess/5919490.jpg
5919732 ZIMMERMANN 123000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919732.jpg
5915841 SELF-PORTRAIT 34965 /content/udrive/MyDrive/GP5/oskelly_imagess/5915841.jpeg
5915847 ISABEL MARANT ETOILE 23540 /content/udrive/MyDrive/GP5/oskelly_imagess/5915847.jpeg
5915838 SELF-PORTRAIT 46904 /content/udrive/MyDrive/GP5/oskelly_imagess/5915838.jpeg
3618121 VALENTINO 34000 /content/udrive/MyDrive/GP5/oskelly_imagess/3618121.jpg
5359745 None None /content/udrive/MyDrive/GP5/oskelly_imagess/5359745.jpeg
5623069 CELINE 22500 /content/udrive/MyDrive/GP5/oskelly_imagess/5623069.jpg
5885036 BURBERRY 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/5885036.jpeg
5915869 SELF-PORTRAIT 38480 /content/udrive/MyDrive/GP5/oskelly_imagess/5915869.jpeg
5191127 GUCCI 80000 /content/udrive/MyDrive/GP5/oskelly_imagess/5191127.jpeg
5055186 BRUNELLO CUCINELLI 250000 /content/udrive/MyDrive/GP5/oskelly_imagess/5055186.jpeg
5919772 ELISABETTA FRANCHI 19000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919772.jpg
5919675 ZIMMERMANN 70000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919675.jpg
4956482 BOGNER 32000 /content/udrive/MyDrive/GP5/oskelly_imagess/4956482.jpg
5919612 ISABEL MARANT ETOILE 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919612.jpg
5919633 ZIMMERMANN 110000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919633.jpg
5919666 ZIMMERMANN 63000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919666.jpg
5919469 SAINT LAURENT 150000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919469.jpg
5919804 WOLFORD 19000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919804.jpg
5644969 MIU MIU 60000 /content/udrive/MyDrive/GP5/oskelly_imagess/5644969.jpg
2839653 ZIMMERMANN 245000 /content/udrive/MyDrive/GP5/oskelly_imagess/2839653.jpg
5919701 BURBERRY 99000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919701.jpg
5919782 CELINE 110000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919782.jpg
5919655 DONDUP 10100 /content/udrive/MyDrive/GP5/oskelly_imagess/5919655.jpg
5843166 MARNI 80000 /content/udrive/MyDrive/GP5/oskelly_imagess/5843166.jpeg
5057488 PRADA 50000 /content/udrive/MyDrive/GP5/oskelly_imagess/5057488.jpg
5895871 STELLA MCCARTNEY 16200 /content/udrive/MyDrive/GP5/oskelly_imagess/5895871.jpeg
5702592 ARCTERYX 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/5702592.jpg
5846287 STELLA MCCARTNEY 12900 /content/udrive/MyDrive/GP5/oskelly_imagess/5846287.jpg
2340304 ROBERTO CAVALLI 61000 /content/udrive/MyDrive/GP5/oskelly_imagess/2340304.jpg
4997778 HERNO 60000 /content/udrive/MyDrive/GP5/oskelly_imagess/4997778.jpg
5709721 WEEKEND MAX MARA 50000 /content/udrive/MyDrive/GP5/oskelly_imagess/5709721.jpg
5709711 MAJE 12500 /content/udrive/MyDrive/GP5/oskelly_imagess/5709711.jpg
4956991 THE NORTH FACE 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/4956991.jpg

In [ ]:
data = pd.DataFrame(all_items)
data.to_excel('all_items_1500-2200_with_images.xlsx', index=False)
data.head()

,Oskelly ID,url,Размер,Раздел,Категория,Бренд,Материал одежды,Цвет,Состояние товара,Продавец,...,Скидка,Описание,Название,Состояние,image_url,image_path,Посадка,Материал джинсов,Модель,Винтаж
0,5829074,https://oskelly.ru/products/longsliv-vetements...,INT M,Женское,Лонгсливы,VETEMENTS,Хлопок,Черный,Отличное состояние,Частный продавец,...,-66%,"Лонгслив Tribal Long Sleeve, состояние новое, ...",VETEMENTSЛонгсливЛонгслив,Отличное состояние,https://static.cdn.oskelly.ru/product/5829074/...,/content/udrive/MyDrive/GP5/oskelly_imagess/58...,NaN,NaN,NaN,NaN
1,5708655,https://oskelly.ru/products/kupalnik-melissa-n...,IT 42,Женское,Купальники,Melissa,Другое,Темно-синий,Новое с биркой,Частный продавец,...,NaN,MELISSA ODABASH новый купальник оригинал 42 it...,MelissaТемно-синий купальникТемно-синий купальник,Новое с биркой,https://static.cdn.oskelly.ru/product/5708655/...,/content/udrive/MyDrive/GP5/oskelly_imagess/57...,NaN,NaN,NaN,NaN
2,5920954,https://oskelly.ru/products/povsednevnoe-plate...,INT S,Женское,Повседневные платья,LOUIS VUITTON,Кашемир,Темно-синий,Отличное состояние,Ресейл магазин,...,NaN,Платье LOUIS VUITTON INT S синий кашемир,LOUIS VUITTONТемно-синее кашемировое повседнев...,Отличное состояние,https://static.cdn.oskelly.ru/product/5920954/...,/content/udrive/MyDrive/GP5/oskelly_imagess/59...,NaN,NaN,NaN,NaN
3,1690337,https://oskelly.ru/products/yubka-mini-miu-miu...,IT 40,Женское,Юбки мини,MIU MIU,Другое,Белый,Отличное состояние,Частный продавец,...,-44%,Мини-юбка Miu-Miu. Роскошная и очень девочкова...,MIU MIUБелая юбка миниБелая юбка мини,Отличное состояние,https://static.cdn.oskelly.ru/product/1690337/...,/content/udrive/MyDrive/GP5/oskelly_imagess/16...,NaN,NaN,NaN,NaN
4,5859263,https://oskelly.ru/products/yubka-maksi-polora...,UK 10,Женское,Юбки макси,POLO RALPH LAUREN,Лен,Синий,Новое с биркой,Частный продавец,...,-29%,POLO RALPH LAUREN новая юбка. Незаменима для ж...,POLO RALPH LAURENСиняя льняная юбка максиСиняя...,Новое с биркой,https://static.cdn.oskelly.ru/product/5859263/...,/content/udrive/MyDrive/GP5/oskelly_imagess/58...,NaN,NaN,NaN,NaN

In [ ]:
all_items = []

for i in range(2200, 3000):
  url = 'https://oskelly.ru' + items.iloc[i, 0]
  oskelly = requests.get(url, headers=headers)

  if oskelly.status_code == 200:
    soup = BeautifulSoup(oskelly.text, 'html')
    item = {}

    item_id = items.iloc[i, 0].split('-')[-1]
    item['Oskelly ID'] = item_id
    item['url'] = url

    for elem in soup.find_all('li', class_='osk-product-attributes__item'):
      name_elem = elem.find('span', class_='osk-product-attributes__item-name')
      value_elem = elem.find('span', class_='osk-product-attributes__item-value')

      if name_elem and value_elem:
        category = name_elem.text.strip()
        value = value_elem.text.strip()
        item[category] = value

    price = soup.find('span', class_='osk-product__rrpPrice')
    if price:
      item['Цена'] = price.text.replace('\xa0', '').replace('₽', '').strip()

    discount = soup.find('span', class_='osk-product__discount')
    if discount:
      item['Скидка'] = discount.text.strip()

    price2 = soup.find('span', class_='osk-product__price')
    if price2 and 'Цена' not in item:
      item['Цена'] = price2.text.replace('\xa0', '').replace('₽', '').strip()


    description = soup.find('div', class_='osk-product-seller__description')
    if description:
      item['Описание'] = description.text.strip()


    brand = soup.find('a', class_='osk-product__brand')
    if brand:
      item['Бренд'] = brand.text.strip()


    title = soup.find('h1', class_='osk-product__title')
    if title:
      item['Название'] = title.text.strip()


    condition = soup.find('div', class_='osk-product__condition')
    if condition:
      item['Состояние'] = condition.text.strip()


    image_url = get_main_product_image_url(soup)
    image_path = download_main_product_image(image_url=image_url,item_id=item_id,images_dir=images_dir)

    item['image_url'] = image_url
    item['image_path'] = image_path

    all_items.append(item)

    print(item_id, item.get('Бренд'), item.get('Цена'), image_path)

  time.sleep(0.5)

5810365 ELISABETTA FRANCHI 37586 /content/udrive/MyDrive/GP5/oskelly_imagess/5810365.jpg
5912972 MAX MARA 42128 /content/udrive/MyDrive/GP5/oskelly_imagess/5912972.jpg
5810252 ELISABETTA FRANCHI 63363 /content/udrive/MyDrive/GP5/oskelly_imagess/5810252.jpg
5843589 DARKPARK 56029 /content/udrive/MyDrive/GP5/oskelly_imagess/5843589.jpg
5912936 MAX MARA 39996 /content/udrive/MyDrive/GP5/oskelly_imagess/5912936.jpg
5803082 7 FOR ALL MANKIND 48013 /content/udrive/MyDrive/GP5/oskelly_imagess/5803082.jpg
1935221 CHANEL 11990 /content/udrive/MyDrive/GP5/oskelly_imagess/1935221.jpg
5810604 ELISABETTA FRANCHI 26693 /content/udrive/MyDrive/GP5/oskelly_imagess/5810604.jpg
5803007 7 FOR ALL MANKIND 26693 /content/udrive/MyDrive/GP5/oskelly_imagess/5803007.jpg
5885880 ELISABETTA FRANCHI 58673 /content/udrive/MyDrive/GP5/oskelly_imagess/5885880.jpg
5810350 ELISABETTA FRANCHI 41617 /content/udrive/MyDrive/GP5/oskelly_imagess/5810350.jpg
5810724 ELISABETTA FRANCHI 41617 /content/udrive/MyDrive/GP5/oskelly_imagess/5810724.jpg
5803206 JIL SANDER 101312 /content/udrive/MyDrive/GP5/oskelly_imagess/5803206.jpg
5919558 None None /content/udrive/MyDrive/GP5/oskelly_imagess/5919558.jpg
5802921 BLAZE MILANO 180196 /content/udrive/MyDrive/GP5/oskelly_imagess/5802921.jpg
5803274 JEJIA 45881 /content/udrive/MyDrive/GP5/oskelly_imagess/5803274.jpg
5810344 ERMANNO SCERVINO 105576 /content/udrive/MyDrive/GP5/oskelly_imagess/5810344.jpg
5811023 SELF-PORTRAIT 51765 /content/udrive/MyDrive/GP5/oskelly_imagess/5811023.jpg
5811464 ROBERTO COLLINA 29336 /content/udrive/MyDrive/GP5/oskelly_imagess/5811464.jpg
5803210 MOORER 107197 /content/udrive/MyDrive/GP5/oskelly_imagess/5803210.jpg
5803243 P.A.R.O.S.H. 62681 /content/udrive/MyDrive/GP5/oskelly_imagess/5803243.jpg
5811419 DRIES VAN NOTEN 92273 /content/udrive/MyDrive/GP5/oskelly_imagess/5811419.jpg
5802960 7 FOR ALL MANKIND 25584 /content/udrive/MyDrive/GP5/oskelly_imagess/5802960.jpg
5803186 MOTHER 41617 /content/udrive/MyDrive/GP5/oskelly_imagess/5803186.jpg
5803137 MM6 MAISON MARGIELA 58673 /content/udrive/MyDrive/GP5/oskelly_imagess/5803137.jpg
5910652 CARHARTT WIP 15690 /content/udrive/MyDrive/GP5/oskelly_imagess/5910652.jpeg
5803245 MM6 MAISON MARGIELA 55432 /content/udrive/MyDrive/GP5/oskelly_imagess/5803245.jpg
5912905 MAX MARA 139177 /content/udrive/MyDrive/GP5/oskelly_imagess/5912905.jpeg
5919538 DOLCE&GABBANA 248000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919538.jpg
5811776 MAX MARA STUDIO 53215 /content/udrive/MyDrive/GP5/oskelly_imagess/5811776.jpg
5811801 MAX MARA 27204 /content/udrive/MyDrive/GP5/oskelly_imagess/5811801.jpg
5803469 BLAZE MILANO 149240 /content/udrive/MyDrive/GP5/oskelly_imagess/5803469.jpg
5803597 ETRO 143952 /content/udrive/MyDrive/GP5/oskelly_imagess/5803597.jpg
5812073 MAX MARA 27204 /content/udrive/MyDrive/GP5/oskelly_imagess/5812073.jpg
5910667 CARHARTT WIP 26770 /content/udrive/MyDrive/GP5/oskelly_imagess/5910667.jpeg
5885481 DOLCE&GABBANA 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5885481.jpg
5803285 P.A.R.O.S.H. 31383 /content/udrive/MyDrive/GP5/oskelly_imagess/5803285.jpg
5812059 ALBERTO BIANI 57564 /content/udrive/MyDrive/GP5/oskelly_imagess/5812059.jpg
5803614 GUEST IN RESIDENCE 52788 /content/udrive/MyDrive/GP5/oskelly_imagess/5803614.jpg
5803316 BRUNELLO CUCINELLI 223859 /content/udrive/MyDrive/GP5/oskelly_imagess/5803316.jpg
4604807 MIU MIU 86700 /content/udrive/MyDrive/GP5/oskelly_imagess/4604807.png
5915071 WEEKEND MAX MARA 18000 /content/udrive/MyDrive/GP5/oskelly_imagess/5915071.jpg
5919527 DOLCE&GABBANA 267000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919527.jpg
5812223 EXTREME CASHMERE 37353 /content/udrive/MyDrive/GP5/oskelly_imagess/5812223.jpg
5912949 MIU MIU 309139 /content/udrive/MyDrive/GP5/oskelly_imagess/5912949.jpg
5812538 MAISON MARGIELA 105576 /content/udrive/MyDrive/GP5/oskelly_imagess/5812538.jpg
5912974 MAX MARA 53897 /content/udrive/MyDrive/GP5/oskelly_imagess/5912974.jpg
5812838 ALBERTO BIANI 88520 /content/udrive/MyDrive/GP5/oskelly_imagess/5812838.jpg
5553932 BURBERRY 18700 /content/udrive/MyDrive/GP5/oskelly_imagess/5553932.jpg
5919516 DOLCE&GABBANA 207000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919516.jpg
1158094 BALMAIN 270000 /content/udrive/MyDrive/GP5/oskelly_imagess/1158094.jpg
4216530 ALEXANDER WANG 68000 /content/udrive/MyDrive/GP5/oskelly_imagess/4216530.jpg
1102766 FABIANA FILIPPI 49000 /content/udrive/MyDrive/GP5/oskelly_imagess/1102766.jpg
1330450 BALMAIN 74000 /content/udrive/MyDrive/GP5/oskelly_imagess/1330450.jpg
1242159 ALICE+OLIVIA 39000 /content/udrive/MyDrive/GP5/oskelly_imagess/1242159.jpg
757371 STELLA MCCARTNEY 67000 /content/udrive/MyDrive/GP5/oskelly_imagess/757371.jpg
5919499 DOLCE&GABBANA 232000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919499.jpg
5888199 KHAITE 263344 /content/udrive/MyDrive/GP5/oskelly_imagess/5888199.jpg
4698096 JOSEPH 49000 /content/udrive/MyDrive/GP5/oskelly_imagess/4698096.jpg
1141513 MAISON KITSUNE 47000 /content/udrive/MyDrive/GP5/oskelly_imagess/1141513.jpg
1540936 OLYMPIA LE TAN 49000 /content/udrive/MyDrive/GP5/oskelly_imagess/1540936.jpg
1096226 DKNY 49000 /content/udrive/MyDrive/GP5/oskelly_imagess/1096226.jpg
690881 HELMUT LANG 43000 /content/udrive/MyDrive/GP5/oskelly_imagess/690881.jpg
1242948 KENZO 43000 /content/udrive/MyDrive/GP5/oskelly_imagess/1242948.jpg
5338998 TOTEME 85000 /content/udrive/MyDrive/GP5/oskelly_imagess/5338998.jpeg
5813935 EMPORIO ARMANI 26693 /content/udrive/MyDrive/GP5/oskelly_imagess/5813935.jpg
5813599 EMPORIO ARMANI 30957 /content/udrive/MyDrive/GP5/oskelly_imagess/5813599.jpg
5803696 ELISABETTA FRANCHI 61828 /content/udrive/MyDrive/GP5/oskelly_imagess/5803696.jpg
5734026 PALM ANGELS 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/5734026.jpg
5842205 BALMAIN 276136 /content/udrive/MyDrive/GP5/oskelly_imagess/5842205.jpg
5803823 BALMAIN 265476 /content/udrive/MyDrive/GP5/oskelly_imagess/5803823.jpg
2253704 BALENCIAGA 65000 /content/udrive/MyDrive/GP5/oskelly_imagess/2253704.jpg
994875 J.W.ANDERSON 56000 /content/udrive/MyDrive/GP5/oskelly_imagess/994875.jpg
727242 STELLA MCCARTNEY 67000 /content/udrive/MyDrive/GP5/oskelly_imagess/727242.jpg
528162 MONCLER 49000 /content/udrive/MyDrive/GP5/oskelly_imagess/528162.jpg
996546 PRABAL GURUNG 76000 /content/udrive/MyDrive/GP5/oskelly_imagess/996546.jpg
171932 3.1 PHILLIP LIM 37000 /content/udrive/MyDrive/GP5/oskelly_imagess/171932.jpg
531033 DOLCE&GABBANA 258800 /content/udrive/MyDrive/GP5/oskelly_imagess/531033.jpg
5919470 THE ROW 122000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919470.jpg
5698339 BOTTEGA VENETA 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/5698339.jpg
5919380 HAIKURE 16500 /content/udrive/MyDrive/GP5/oskelly_imagess/5919380.jpg
5919388 ROBERTO CAVALLI 20000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919388.jpg
5918427 LOUIS VUITTON 19500 /content/udrive/MyDrive/GP5/oskelly_imagess/5918427.jpg
5918774 ELISABETTA FRANCHI 15000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918774.jpg
5919395 HAIKURE 16500 /content/udrive/MyDrive/GP5/oskelly_imagess/5919395.jpg
5919328 JUST CAVALLI 42000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919328.jpg
5919282 UMA WANG 50000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919282.jpg
5919391 ALO YOGA 13500 /content/udrive/MyDrive/GP5/oskelly_imagess/5919391.jpg
5919398 ROBERTO CAVALLI 34000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919398.jpg
5903435 GIUSEPPE DI MORABITO 74100 /content/udrive/MyDrive/GP5/oskelly_imagess/5903435.jpg
5919440 THE ROW 145000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919440.jpg
5628059 PINKO 32000 /content/udrive/MyDrive/GP5/oskelly_imagess/5628059.jpeg
5148659 12 STOREEZ 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/5148659.jpg
2452660 BURBERRY 95000 /content/udrive/MyDrive/GP5/oskelly_imagess/2452660.jpg
5804340 BURBERRY 308116 /content/udrive/MyDrive/GP5/oskelly_imagess/5804340.jpg
5511266 ELISABETTA FRANCHI 13000 /content/udrive/MyDrive/GP5/oskelly_imagess/5511266.jpg
5813934 EMPORIO ARMANI 73596 /content/udrive/MyDrive/GP5/oskelly_imagess/5813934.jpg
5813739 PATRIZIA PEPE 26693 /content/udrive/MyDrive/GP5/oskelly_imagess/5813739.jpg
5814253 SELF-PORTRAIT 35732 /content/udrive/MyDrive/GP5/oskelly_imagess/5814253.jpg
5919363 CULT GAIA 55000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919363.jpg
5919039 FENDI 24900 /content/udrive/MyDrive/GP5/oskelly_imagess/5919039.jpg
5919278 CULT GAIA 12500 /content/udrive/MyDrive/GP5/oskelly_imagess/5919278.jpg
5814429 ELISABETTA FRANCHI 69332 /content/udrive/MyDrive/GP5/oskelly_imagess/5814429.jpg
4908772 CARHARTT 24000 /content/udrive/MyDrive/GP5/oskelly_imagess/4908772.jpeg
2209740 VALENTINO 49000 /content/udrive/MyDrive/GP5/oskelly_imagess/2209740.jpg
5918241 PINKO 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918241.jpg
5919379 ALO YOGA 14000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919379.jpg
5919291 CULT GAIA 47000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919291.jpg
5919054 SPORTMAX 15000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919054.jpg
5919362 ALO YOGA 13500 /content/udrive/MyDrive/GP5/oskelly_imagess/5919362.jpg
5919346 ALO YOGA 29000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919346.jpg
5919375 HELMUT LANG 24000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919375.jpg
5919057 MAX MARA 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919057.jpg
5912662 LANVIN 53340 /content/udrive/MyDrive/GP5/oskelly_imagess/5912662.jpg
5919352 ALEXANDER WANG 28000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919352.jpg
5919032 None None /content/udrive/MyDrive/GP5/oskelly_imagess/5919032.jpeg
5887072 VALENTINO 106000 /content/udrive/MyDrive/GP5/oskelly_imagess/5887072.jpg
5918873 PRADA 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918873.jpg
5917768 FUJIFILM 42500 /content/udrive/MyDrive/GP5/oskelly_imagess/5917768.jpg
5919031 VERSACE 15720 /content/udrive/MyDrive/GP5/oskelly_imagess/5919031.jpg
5919067 MAJE 19000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919067.jpg
5918206 SANDRO 28000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918206.jpg
5918221 TWIN-SET 28000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918221.jpg
5919068 WEEKEND MAX MARA 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919068.jpg
5919128 COS 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919128.jpg
5919260 MARNI 72000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919260.jpg
5919236 CULT GAIA 18500 /content/udrive/MyDrive/GP5/oskelly_imagess/5919236.jpg
5919274 JEAN PAUL GAULTIER 60000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919274.jpg
5918864 PRADA 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918864.jpg
5919026 ETRO 14290 /content/udrive/MyDrive/GP5/oskelly_imagess/5919026.jpg
5919317 HELMUT LANG 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919317.jpg
5919072 WEEKEND MAX MARA 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919072.jpg
5919052 ALAIA 10000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919052.jpg
5913974 CELINE 128500 /content/udrive/MyDrive/GP5/oskelly_imagess/5913974.jpg
5919111 BALENCIAGA 100000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919111.jpg
5919117 FENDI 150000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919117.jpg
5918998 Gallery Dept 66670 /content/udrive/MyDrive/GP5/oskelly_imagess/5918998.jpg
5919024 St. Barth 12500 /content/udrive/MyDrive/GP5/oskelly_imagess/5919024.jpg
5919140 MIU MIU 40000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919140.jpg
5917284 CHANEL 515000 /content/udrive/MyDrive/GP5/oskelly_imagess/5917284.jpg
5917292 CHANEL 515000 /content/udrive/MyDrive/GP5/oskelly_imagess/5917292.jpg
5919136 FENDI 110000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919136.jpg
5918365 LORO PIANA 49000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918365.jpg
5919176 FARM RIO 38000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919176.jpg
5918245 SANDRO 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918245.jpg
5918279 ELISABETTA FRANCHI 65800 /content/udrive/MyDrive/GP5/oskelly_imagess/5918279.jpg
5918224 TWIN-SET 28000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918224.jpg
5918197 POLO RALPH LAUREN 27000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918197.jpg
5918339 CHANEL 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918339.jpg
5918268 IRO 35800 /content/udrive/MyDrive/GP5/oskelly_imagess/5918268.jpg
948957 MONCLER 85000 /content/udrive/MyDrive/GP5/oskelly_imagess/948957.jpg
3907616 SANDRO 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/3907616.jpg
1339820 T BY ALEXANDER WANG 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/1339820.jpg
5498130 ADIDAS 22000 /content/udrive/MyDrive/GP5/oskelly_imagess/5498130.jpg
946702 ACNE STUDIOS 13500 /content/udrive/MyDrive/GP5/oskelly_imagess/946702.jpeg
5211301 BRUNELLO CUCINELLI 75000 /content/udrive/MyDrive/GP5/oskelly_imagess/5211301.jpeg
5210756 BRUNELLO CUCINELLI 75000 /content/udrive/MyDrive/GP5/oskelly_imagess/5210756.jpg
5211008 BRUNELLO CUCINELLI 75000 /content/udrive/MyDrive/GP5/oskelly_imagess/5211008.jpeg
5211532 BRUNELLO CUCINELLI 310000 /content/udrive/MyDrive/GP5/oskelly_imagess/5211532.jpg
5715181 OFF-WHITE 45000 /content/udrive/MyDrive/GP5/oskelly_imagess/5715181.jpg
5804414 MAISON MARGIELA 137556 /content/udrive/MyDrive/GP5/oskelly_imagess/5804414.jpg
5804361 GIORGIO ARMANI 223859 /content/udrive/MyDrive/GP5/oskelly_imagess/5804361.jpg
5484177 LEVI'S 28000 /content/udrive/MyDrive/GP5/oskelly_imagess/5484177.jpg
5805230 NISSA 79651 /content/udrive/MyDrive/GP5/oskelly_imagess/5805230.jpg
5805122 ELISABETTA FRANCHI 30957 /content/udrive/MyDrive/GP5/oskelly_imagess/5805122.jpg
5805052 PESERICO 37267 /content/udrive/MyDrive/GP5/oskelly_imagess/5805052.jpg
5919404 THE ROW 481000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919404.jpg
5804874 MAX MARA 41617 /content/udrive/MyDrive/GP5/oskelly_imagess/5804874.jpg
5805247 PATRIZIA PEPE 17056 /content/udrive/MyDrive/GP5/oskelly_imagess/5805247.jpg
5919392 VETEMENTS 33340 /content/udrive/MyDrive/GP5/oskelly_imagess/5919392.png
5919378 THE ATTICO 22000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919378.jpg
3984970 BALENCIAGA 21000 /content/udrive/MyDrive/GP5/oskelly_imagess/3984970.jpg
5919331 ALEXANDER WANG 45000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919331.jpg
2389126 BALMAIN 95000 /content/udrive/MyDrive/GP5/oskelly_imagess/2389126.jpg
5805130 BRUNELLO CUCINELLI 138580 /content/udrive/MyDrive/GP5/oskelly_imagess/5805130.jpg
5804715 7 FOR ALL MANKIND 32825 /content/udrive/MyDrive/GP5/oskelly_imagess/5804715.jpg
5805121 PATRIZIA PEPE 20808 /content/udrive/MyDrive/GP5/oskelly_imagess/5805121.jpg
5805214 DITA 125788 /content/udrive/MyDrive/GP5/oskelly_imagess/5805214.jpg
5805192 FENDI 266499 /content/udrive/MyDrive/GP5/oskelly_imagess/5805192.jpg
5805257 HERNO 54920 /content/udrive/MyDrive/GP5/oskelly_imagess/5805257.jpg
5805307 LIU JO 19103 /content/udrive/MyDrive/GP5/oskelly_imagess/5805307.jpg
5807296 ERMANNO FIRENZE 57564 /content/udrive/MyDrive/GP5/oskelly_imagess/5807296.jpg
5807545 ALYSI 54409 /content/udrive/MyDrive/GP5/oskelly_imagess/5807545.jpg
5807188 LORENA ANTONIAZZI 82124 /content/udrive/MyDrive/GP5/oskelly_imagess/5807188.jpg
5807469 MOORER 126896 /content/udrive/MyDrive/GP5/oskelly_imagess/5807469.jpg
5807567 ELISABETTA FRANCHI 34112 /content/udrive/MyDrive/GP5/oskelly_imagess/5807567.jpg
5918885 KITON 79800 /content/udrive/MyDrive/GP5/oskelly_imagess/5918885.jpg
5807703 MAX MARA 58673 /content/udrive/MyDrive/GP5/oskelly_imagess/5807703.jpg
3440714 DIESEL 85000 /content/udrive/MyDrive/GP5/oskelly_imagess/3440714.jpg
5913939 CELINE 68900 /content/udrive/MyDrive/GP5/oskelly_imagess/5913939.jpeg
5497732 DIESEL 85000 /content/udrive/MyDrive/GP5/oskelly_imagess/5497732.jpg
5807483 MAX MARA 40508 /content/udrive/MyDrive/GP5/oskelly_imagess/5807483.jpg
5807192 ERMANNO FIRENZE 68821 /content/udrive/MyDrive/GP5/oskelly_imagess/5807192.jpg
5807863 STELLA MCCARTNEY 158876 /content/udrive/MyDrive/GP5/oskelly_imagess/5807863.jpg
5919307 CHROME HEARTS 160000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919307.jpg
5914483 ALO YOGA 14000 /content/udrive/MyDrive/GP5/oskelly_imagess/5914483.jpg
5807572 MAX MARA 105576 /content/udrive/MyDrive/GP5/oskelly_imagess/5807572.jpg
312762 BLUMARINE 21000 /content/udrive/MyDrive/GP5/oskelly_imagess/312762.jpg
5807103 LORENA ANTONIAZZI 101312 /content/udrive/MyDrive/GP5/oskelly_imagess/5807103.jpg
3947473 SAINT LAURENT 37000 /content/udrive/MyDrive/GP5/oskelly_imagess/3947473.jpg
5807890 MONCLER 106088 /content/udrive/MyDrive/GP5/oskelly_imagess/5807890.jpg
2265694 CARHARTT 18000 /content/udrive/MyDrive/GP5/oskelly_imagess/2265694.png
5807608 'S MAX MARA 65580 /content/udrive/MyDrive/GP5/oskelly_imagess/5807608.jpg
5824099 ALYSI 24561 /content/udrive/MyDrive/GP5/oskelly_imagess/5824099.jpg
5163669 LEVI'S 26000 /content/udrive/MyDrive/GP5/oskelly_imagess/5163669.jpeg
5710427 GUCCI 11000 /content/udrive/MyDrive/GP5/oskelly_imagess/5710427.jpeg
5723457 MICHAEL MICHAEL KORS 13000 /content/udrive/MyDrive/GP5/oskelly_imagess/5723457.jpg
5870426 GOLDEN GOOSE 44772 /content/udrive/MyDrive/GP5/oskelly_imagess/5870426.jpg
5811354 MONCLER 111972 /content/udrive/MyDrive/GP5/oskelly_imagess/5811354.jpg
5902452 GUCCI 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/5902452.jpg
5918913 GUCCI 220000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918913.jpg
5919017 MAX&CO 13000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919017.jpg
5919048 VERSACE 175000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919048.jpg
5918966 BOUTIQUE MOSCHINO 76000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918966.jpg
5919015 MAX MARA 15000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919015.jpg
5919009 HAIDER ACKERMANN 30000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919009.jpg
1051187 GUCCI 45000 /content/udrive/MyDrive/GP5/oskelly_imagess/1051187.png
5919157 KHAITE 115000 /content/udrive/MyDrive/GP5/oskelly_imagess/5919157.jpg
5884293 ALO YOGA 28000 /content/udrive/MyDrive/GP5/oskelly_imagess/5884293.jpeg
5918976 MARQUES' ALMEIDA 15000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918976.jpg
1831044 DOLCE&GABBANA 195000 /content/udrive/MyDrive/GP5/oskelly_imagess/1831044.jpg
5904537 JIL SANDER 89000 /content/udrive/MyDrive/GP5/oskelly_imagess/5904537.jpg
5904643 RALPH LAUREN 29000 /content/udrive/MyDrive/GP5/oskelly_imagess/5904643.jpg
5885883 MAX MARA 85280 /content/udrive/MyDrive/GP5/oskelly_imagess/5885883.jpg
5904703 BARBOUR 45000 /content/udrive/MyDrive/GP5/oskelly_imagess/5904703.jpg
5904542 ESCADA 54000 /content/udrive/MyDrive/GP5/oskelly_imagess/5904542.jpg
5904550 RALPH LAUREN 21000 /content/udrive/MyDrive/GP5/oskelly_imagess/5904550.jpg
5904713 JIL SANDER 132000 /content/udrive/MyDrive/GP5/oskelly_imagess/5904713.jpg
5904597 FALCONERI 59000 /content/udrive/MyDrive/GP5/oskelly_imagess/5904597.jpg
5904530 MAX MARA 78000 /content/udrive/MyDrive/GP5/oskelly_imagess/5904530.jpg
4632696 EMPORIO ARMANI 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/4632696.jpg
5904688 POLO RALPH LAUREN 29000 /content/udrive/MyDrive/GP5/oskelly_imagess/5904688.jpg
4632660 EMPORIO ARMANI 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/4632660.jpg
5904709 PAUL & SHARK 59000 /content/udrive/MyDrive/GP5/oskelly_imagess/5904709.jpg
4632682 EMPORIO ARMANI 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/4632682.jpg
5917475 BA&SH 26000 /content/udrive/MyDrive/GP5/oskelly_imagess/5917475.jpg
5918908 KENZO 35000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918908.jpg
5918903 ALEXANDER TEREKHOV 85000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918903.jpg
5918891 MARNI 75000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918891.jpg
5918884 CHLOE 11000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918884.jpg
5918854 MIU MIU 155000 /content/udrive/MyDrive/GP5/oskelly_imagess/5918854.jpg
4632678 EMPORIO ARMANI 25000 /content/udrive/MyDrive/GP5/oskelly_imagess/4632678.jpg
5904651 BARBOUR 32000 /content/udrive/MyDrive/GP5/oskelly_imagess/5904651.jpg
5811240 Eleh 20467 /content/udrive/MyDrive/GP5/oskelly_imagess/5811240.jpg

In [ ]:
data = pd.DataFrame(all_items)
data.to_excel('all_items_2200-3000_with_images.xlsx', index=False)
data.head()

,Oskelly ID,url,Размер,Раздел,Категория,Бренд,Материал одежды,Цвет,Состояние товара,Продавец,...,Описание,Название,Состояние,image_url,image_path,Посадка,Скидка,Материал джинсов,Винтаж,Модель
0,5810365,https://oskelly.ru/products/shorty-elisabettaf...,IT 40/42/44,Женское,Шорты,ELISABETTA FRANCHI,Вискоза,Коричневый,Новое с биркой,Бутик,...,Shorts\n\nCocoa alligator pattern logo button ...,ELISABETTA FRANCHIКоричневые вискозные шортыКо...,Новое с биркой,https://static.cdn.oskelly.ru/product/5810365/...,/content/udrive/MyDrive/GP5/oskelly_imagess/58...,NaN,NaN,NaN,NaN,NaN
1,5912972,https://oskelly.ru/products/pryamye-bryuki-max...,INT L/XL,Женское,Прямые брюки,MAX MARA,Полиамид,Синий,Новое с биркой,Бутик,...,MIDNIGHT BLUE KNIT STRILLO WIDE-LEG PANT,MAX MARAСиние полиамидовые прямые брюкиСиние п...,Новое с биркой,https://static.cdn.oskelly.ru/product/5912972/...,/content/udrive/MyDrive/GP5/oskelly_imagess/59...,Средняя,-30%,NaN,NaN,NaN
2,5810252,https://oskelly.ru/products/plate-elisabettafr...,IT 38/40/44,Женское,Другие платья,ELISABETTA FRANCHI,Хлопок,Желтый,Новое с биркой,Бутик,...,Flared Skirt Midi Dress In Yellow Cotton\n\nMi...,ELISABETTA FRANCHIЖелтое хлопковое платьеЖелто...,Новое с биркой,https://static.cdn.oskelly.ru/product/5810252/...,/content/udrive/MyDrive/GP5/oskelly_imagess/58...,NaN,-11%,NaN,NaN,NaN
3,5843589,https://oskelly.ru/products/pryamye-dzhinsy-da...,JEANS 28,Женское,Прямые джинсы,DARKPARK,NaN,Голубой,Новое с биркой,Бутик,...,Джинсы Ines\n\nДжинсы из хлопкового денима с э...,DARKPARKГолубые хлопковые прямые джинсыГолубые...,Новое с биркой,https://static.cdn.oskelly.ru/product/5843589/...,/content/udrive/MyDrive/GP5/oskelly_imagess/58...,Средняя,-3%,Хлопок,NaN,NaN
4,5912936,https://oskelly.ru/products/yubka-maksi-maxmar...,IT 40,Женское,Юбки макси,MAX MARA,Полиамид,Белый,Новое с биркой,Бутик,...,WHITE JERSEY VERNICE SKIRT,MAX MARAБелая полиамидовая юбка максиБелая пол...,Новое с биркой,https://static.cdn.oskelly.ru/product/5912936/...,/content/udrive/MyDrive/GP5/oskelly_imagess/59...,NaN,-29%,NaN,NaN,NaN